viaacode/hetarchief-client

- .eslintrc.js
* Interfaces moeten niet met `I` geprefixed worden.
> feat(linter): interfaces should not be prefixed with I

- scripts/path-aliases.js
- src/modules/media/hooks/get-media-objects.ts
- src/modules/media/services/index.ts
- src/modules/media/services/media/index.ts
- src/modules/media/services/media/media.service.const.ts
- src/modules/media/services/media/media.service.ts
- src/modules/media/types/index.ts
- src/modules/media/utils/index.ts
- src/modules/media/utils/map-filters/index.ts
- src/modules/media/utils/map-filters/map-filters.test.tsx
- src/modules/media/utils/map-filters/map-filters.tsx
- src/modules/navigation/components/Navigation/NavigationDropdown/NavigationDropdown.tsx
- src/modules/reading-room/components/FilterMenu/FilterMenu.types.ts
- src/modules/reading-room/hooks/get-reading-rooms.ts
- src/modules/reading-room/services/reading-room/reading-room.service.ts
- src/modules/reading-room/types/index.ts
- src/modules/shared/components/MediaCard/MediaCard.types.ts
- src/modules/shared/const/query-keys.ts
- src/modules/shared/services/api-service/api.service.ts
- src/modules/shared/types/api.ts
- src/pages/index.tsx
- src/pages/leeszaal/[readingRoomSlug]/index.tsx
- tsconfig.json
before the user searches:
when they search:
when they switch tabs it currently shows all items, since we cannot search by media type yet:
> feat(arc-294): search media items using elasticsearch endpoint

- .env.template
- next.config.js
- src/modules/auth/services/auth-service/auth.service.ts
- src/modules/config/const/index.ts
- src/modules/shared/store/store.ts
- src/modules/shared/types/global.d.ts
- Fix missing origin env var (get it through publicRuntimeConfig instead of process.env)
- renamed NEXT_PUBLIC_ORIGIN to CLIENT_URL (more in line with PROXY_URL)
- Switch production check to BUILD_TOOLS === 'true' check (in case we ever want to enable build tools on production)
- Add better type checking for process.env, so we don't need to mirror env vars in a separate config.ts file
> fix(env-vars): fix env vars for tst

- src/styles/base/_reset.scss
https://kilianvalkhof.com/2022/css-html/your-css-reset-needs-text-size-adjust-probably/
https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust
Some mobile browsers enlarge the default text to improve readability. This was relevant when web was not optimised for mobile. This stops that default behaviour and prevents an inflated look in most mobile browsers.
> feat(mobile): prevent mobile browsers from inflating text

- .storybook/preview.js
* Added i18n support for storybook so we don't have long translation keys in some components
> feat(storybook): add i18n provider as global decorator

- src/modules/navigation/components/Navigation/Navigation.module.scss
> fix(navigation-header): move separator line up 1 pixel

- src/modules/navigation/components/Navigation/Navigation.consts.tsx
> feat(arc-392): hide divider when user has no access to any reading rooms

- src/modules/home/components/LoggedInHome/LoggedInHome.tsx
Invalid href passed to next/router:
//gebruiksvoorwaarden?redirectTo=%2F%3Fbezoekersruimte%3Dvrt,
repeated forward-slashes (//) or backslashes \ are not valid in the href
> fix(logged-in-home): remove double slash in tos redirect

- src/modules/account/services/collections/collections.service.ts
This makes the query a bit more efficient
Related PR: https://github.com/viaacode/hetarchief-proxy/pull/173
> fix(arc-213): Do not send %% if query in folder is empty

- src/modules/reading-room/components/FilterMenu/FilterMenuMobile/FilterMenuMobile.tsx
[ARC-627](https://meemoo.atlassian.net/browse/ARC-627)
- Mobile filter menu icon position on safari
> fix(arc-627): mobile filter icon position on safari

- src/modules/media/const/index.tsx
- src/modules/media/utils/render-with-new-lines.tsx
- src/modules/shared/components/TextWithNewLines/TextWithNewLines.tsx
- src/modules/shared/components/TextWithNewLines/index.ts
- src/modules/shared/components/index.ts
- src/pages/[slug]/[ie]/index.tsx
You can test this by manually updating an object description in the database:
http://localhost:3200/vrt/49b1bf8894004fd49aeaba36cfc5a958d5c32a4566244999a862e80b498a2c7c7bee152896204294938534fc7f3c6793
> fix(arc-708): Correctly render new lines in description and abstract

- src/modules/media/const/index.tsx
[ARC-803](https://meemoo.atlassian.net/browse/ARC-803)
- `Uitgebreide beschrijving` enkel zichtbaar als de waarde niet leeg is
⚠️ 
- Dit is niet nodig voor de gewone description omdat `TextWithNewLines` `null` terug geeft.
- Wel nodig in `METADATA_FIELDS` omdat de return value nog steeds een ReactNode is.
> fix(arc-803): hide empty descriptions

- src/modules/shared/components/TextWithNewLines/TextWithNewLines.tsx
https://meemoo.atlassian.net/browse/ARC-708
before:
after:
> fix(avo-708): fix double new lines in object description and abstract

- src/pages/[slug]/[ie]/index.tsx
Representations are missing if the object doesn't have a valid license to show essence.
See also: https://github.com/viaacode/hetarchief-proxy/pull/179
> feat(arc-670): licenses

- src/modules/shared/services/notifications-service/notifications.service.test.ts
- src/modules/shared/services/notifications-service/notifications.service.ts
https://meemoo.atlassian.net/browse/ARC-762
* Check if initial notifications have been loaded => don't show notification for first fetch
* if first fetch is empty array => still counts as first fetch
* Add tests
> fix(arc-762): fix initial notifications check

- src/modules/home/components/LoggedInHome/LoggedInHome.tsx
- src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
https://meemoo.atlassian.net/browse/ARC-730
* Remove the reset blade call on close
* Don't close the blade manually, let next just navigate to the other page => less noticeable switch to home page
* Minor optimization of props syntax in Blade
https://user-images.githubusercontent.com/1710840/167145764-d94d3f43-83da-4dad-a557-1c7dbb7e9869.mp4
> fix(arc-730): Reset blade before it opens instead of when it closes

- src/pages/cookiebeleid/index.tsx
I'm assuming cookiebot does not want to load on localhost
We'll see if it starts working on QAS
Translations do not show any *** anymore
> fix(arc-161): fix cookie policy translations

- src/modules/admin/wrappers/with-admin-core-config.tsx
after editing a content page, the app should navigate to the detail view
* Integrate the config service.router functions 
* Integrate the config service.toatService functions
> fix(arc-611): fix router functions in admin core config object

- src/modules/shared/hooks/use-window-size/use-window-size.ts
- src/styles/layouts/_app.scss
- Prevent ui scroll on mobile browsers
⚠️  Test on real device or simulator
> fix(arc-857): stop ui scroll on detail page

- src/pages/[slug]/[ie]/index.tsx
Partially solves: https://meemoo.atlassian.net/browse/ARC-818
Fix error when getting schema identifier of first file, but first file does not exist
```
framework-79bce4a3a540b080.js:1 TypeError: Cannot read properties of undefined (reading 'schemaIdentifier')
at [ie]-5bea180606a15db3.js:1:25295
at Array.filter (<anonymous>)
at [ie]-5bea180606a15db3.js:1:25231
at oo (framework-79bce4a3a540b080.js:1:59417)
at Wo (framework-79bce4a3a540b080.js:1:68984)
at Ku (framework-79bce4a3a540b080.js:1:112708)
at Li (framework-79bce4a3a540b080.js:1:98958)
at Ni (framework-79bce4a3a540b080.js:1:98886)
at Pi (framework-79bce4a3a540b080.js:1:98749)
at bi (framework-79bce4a3a540b080.js:1:95715)
```
> fix(arc-818): Safely get schema identifier of file when does not exist

- src/modules/visitor-space/components/FilterMenu/FilterMenuMobile/FilterMenuMobile.module.scss
- src/styles/pages/_visitor-space.scss
* Add scroll for mobile filters when they get too large
* Increase the padding for the empty placeholder on mobile and desktop
Also changed the placeholder positioning on desktop. Centered vertically against the filters, instead of vertically on the screen.
Before:
after:
original design:
> fix(arc-371): Enable scroll when filter menu becomes too large + margins

- src/modules/visits/hooks/update-visit.ts
- src/pages/admin/bezoekersruimtesbeheer/actieve-bezoekers/index.tsx
* Only show active visitors if their request was approved
* Clear the cache for visit requests when a visit mutation is triggered
> fix(arc-736): only show approved visitors, reset visit requests cache

- src/styles/components/_tab.scss
[ARC-395](https://meemoo.atlassian.net/browse/ARC-395?focusedCommentId=31740)
- Betere outline voor de tabs zodat op safari het eerste item ook een outline krijgt na focus.
- Volledig niet kunnen tabben op Safari kan ik nog steeds niet reproduceren.
https://user-images.githubusercontent.com/85545258/171641408-4f1d2e43-042b-4a28-9fb3-6332198bcb95.mp4
> feat(arc-395): show outline on first tab element

- src/pages/admin/gebruikersbeheer/permissies/index.module.scss
- src/pages/admin/gebruikersbeheer/permissies/index.tsx
Add save button at the bottom of the user groups permissions page:
> feat(arc-596): add save button at the bottom of the page (permission)

- src/modules/shared/components/UnreadMarker/UnreadMarker.module.scss
https://meemoo.atlassian.net/browse/ARC-847
before and after:
> fix(arc-847): ensure active visitor indicator is always round

- src/styles/abstracts/_variables.scss
- src/styles/base/_typography.scss
- src/styles/pages/content-pages/_index.scss
https://meemoo.atlassian.net/browse/ARC-444
requires admin core PR: https://github.com/viaacode/react-admin-core-module/pull/29
> fix(arc-444): add h6 styles and colored links in richTextEditor content

- src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
https://meemoo.atlassian.net/jira/software/c/projects/ARC/issues/ARC-981
cannot be tested locally because we do not have enough search results.
The problem:
Go to search on QAS en goto page 4
Scroll back to the top and add a filter:
Scroll back down:
Current result: the page is still on page 4
Desired result: the page is reset to page 1
> fix(arc-981): reset page when filters/sorting changes on search page

- src/pages/[slug]/[ie]/index.tsx
go to this url without access to the space:
https://bezoek.hetarchief.be/vrt/00a22a093585457aaaf7116b9ae32e60a3cf03960ba549a5a87ac757970f541a395784b393be4d49a4e523b11c974c7c
currently: unexpected error => react crash on cannot read includes of undefined: license.includes(
desired: you should see no access screen
> fix(detail-page-error): safely get licenses if obj does not exist

- src/styles/pages/admin/_content-pages-preview.scss
https://meemoo.atlassian.net/browse/ARC-1034
before:
after:
> fix(arc-1034): make copyright text smaller for content page image block

- src/modules/visitor-space/components/PublishedFilterForm/PublishedFilterForm.tsx
https://meemoo.atlassian.net/browse/ARC-1082
before:
after:
> fix(arc-1082): hide filter labels for publish date

- src/styles/base/_root.scss
https://meemoo.atlassian.net/browse/ARC-1061
Dit scrollbar issue is nogal delicaat aangezien we specifiek die overflow scroll erin gestoken hebben om jumpen van de header menu items te vermijden.
Deze oplossing lijkt beter op chrome en edge, maar test het nog eens op mac (safari en chrome).
Er is vaak een jump bij initial page load, maar erna dan niet meer bij het toggelen van een menu.
before chrome & edge:
https://user-images.githubusercontent.com/1710840/186110893-fd8c6a55-bd85-43b1-bf96-afb5c253e36c.mp4
after chrome & edge:
https://user-images.githubusercontent.com/1710840/186110907-da4f5097-c90c-4ae7-9153-802d92afabf6.mp4
> fix(arc-1061): avoid double scrollbar on item detail page on edge

- src/modules/shared/components/Blade/Blade.tsx
https://meemoo.atlassian.net/browse/ARC-1025
Requires components PR: https://github.com/viaacode/react-components/pull/66
This PR adds a hack to attempt to hide the outline on the close button of the notification center blade on ios after opening the profile dropdown.
This hack has not been tested since i couldn't get the vpn to work with browserstack local. 
@ian-emsens-shd if you manage to get it working while testing this PR, let me know the settings?
> fix(arc-1025): add and remove tab index on blade close button

- src/modules/shared/const/index.ts
https://meemoo.atlassian.net/browse/ARC-1093
dates before 1970 in unix format are negative, breaking the split on separator logic
when selecting 4 sept 1924:
before:
after:
> fix(arc-1093): make date separator two dashes to avoid malformed dates

- src/modules/media/const/index.tsx
- src/modules/media/types/index.ts
https://meemoo.atlassian.net/browse/ARC-885
requires proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/244
> fix(arc-885): show correct alternate name for object

- package-lock.json
- src/modules/shared/components/Html/Html.module.scss
- src/modules/shared/components/Html/Html.tsx
- src/styles/components/_html.scss
- src/styles/components/_index.scss
since nextjs tries to serverside render pages, it loads the Html component
which in turn loads it's module scss,
which will try to add a style node to the document head, but document does not exist server side,
so it crashes and the page instead loads a 404 page
I'm not sure why this is not an issue with other module scss components
You can see the error by checking out develop and surfing to:
http://localhost:3200/account/mijn-mappen/favorieten
```
error - (middleware)\node_modules\next\dist\build\webpack\loaders\next-style-loader\runtime\injectStylesIntoStyleTag.js (80:0) @ <unknown>
ReferenceError: document is not defined
```
> fix(arc-964): avoid module css in Html component

- src/modules/auth/wrappers/with-auth/with-auth.tsx
- src/modules/media/services/media/media.service.ts
- src/modules/shared/helpers/render-og-tags.tsx
- src/modules/shared/hooks/use-element-size/use-element-size.ts
- src/modules/shared/hooks/use-isomorphic-layout-effect.ts
- src/pages/[slug]/[ie]/index.tsx
https://meemoo.atlassian.net/browse/ARC-542
requires proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/259
example url: http://localhost:3200/vlaams-parlement/d7d7841f8ad946f8bfa5116b30b9041ccec8fc5521d2404cab08b86c2d41466e231c382d924942de8d586b2f713e85f5
Server side rendered html now correctly contains the SEO tags like title, description, og tags
Switches SEO from client side to server side rendering for the object detail page.
This is a proof of concept. If you guys approve with the approach, ill apply it for all pages.
> fix(avo-542): fix server side rendering for object detail

- src/modules/shared/components/MetaDataDescription/MetaDataDescription.module.scss
https://meemoo.atlassian.net/browse/ARC-1279
page: http://localhost:3200/zoeken/vlaams-parlement/d1288c82c96747d7bb6bd6260c4e2db14bcad026f9cf4add9376c22a5c06db421985e236d7fb4b839ffcf2fbe88606cf
on windows the scrollbar for the description of an object inside a blade is a bit strangely positioned:
This PR fixes that:
> fix(arc-1279): move scrollbar right in read more description blade

- src/modules/auth/services/auth-service/auth.service.ts
- src/modules/shared/const/routes.ts
steps:
* be a logged out user
* click on search
* some requests fail because you need permissions (separate bug)
* you are shown the login modal
* login
* after login you are redirected to /bezoek/zoeken instead of /zoeken
> fix(routing): redirect to after login instead of /bezoek/some other path

- src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
Translations provide 2 functions:
tHtml and tText
tText will output text
tHtml will output a ReactNode with the rendered html
So you cannot use tHtml inside a string
Also the translations need to be fetched from the backend before we can start translating strings, so you always need to fetch translations inside a function and never directly in a const variable on the file level, otherwise it won't correctly be translated.
eg:
```typescript
const myTranslation = tText(....) // wrong
const getMyTranslation = () => tText(...) // correct
```
before:
after:
> fix(translations): use translations in a function and no tHtml in text

- src/modules/visits/hooks/get-active-visit-for-user-and-space.ts
- src/pages/zoeken/[slug]/[ie]/index.tsx
No need to make a call to the api to check if a active visitor request exists, since we're an anonymous user, so the answer is be default: no
so we can immediately return null
> fix: avoid 403 error on call for anonymous users

- src/styles/components/_breadcrumbs.scss
Truncate breadcrumbs:
- default -> max length = 1 line
- active/last item -> max length = 2 lines
> feat(breadcrumbs): truncate breadcrumbs

- src/pages/admin/navigatie/[navigationBarId]/[navigationItemId]/bewerk/index.tsx
> fix(navigation): remove rogue icon on the navigation item edit page

- src/modules/ie-objects/utils/extract-snippet-by-search-term.test.ts
- src/modules/ie-objects/utils/extract-snippet-by-search-term.ts
https://meemoo.atlassian.net/browse/ARC-1422
Make sure if the search term case does not match the description case, the search still works
> fix(arc-1422): make extract snippet helper case insensitive

- src/modules/ie-objects/const/index.tsx
- src/pages/zoeken/[slug]/[ie]/index.tsx
**Kiosk users || all other users when no access to the space of the current object**
**All other users when given access to the space of the current object**
**To test**
Can't be tested by using a kiosk account since there's something wrong with the acc. You can test this by inverting the `isNotKiosk` boolean in `renderMaintainerMetaTitle` and `renderMaintainerMetaData`.
> feat(ie): show simplified maintainer metadata for kiosk users

- src/modules/navigation/components/Navigation/Navigation.module.scss
Margin between 'Zoeken', 'Bezoek...', 'Over het archief' , ... was 0.
> fix(arc-1187): fix navigation bar items margin

- src/modules/admin/layouts/AdminLayout/AdminLayout.module.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1611
> fix(arc-1611): set title on 1 line if enough space in admin screens

- src/modules/ie-objects/const/index.tsx
Ticket: https://meemoo.atlassian.net/browse/ARC-1661
> fix(arc-1661): add tooltip to export metadata action

- src/modules/shared/components/MediaCard/MediaCard.tsx
> feat(MediaCard): always render labels

- src/modules/shared/types/ie-objects.ts
- src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
- src/modules/visitor-space/utils/elastic-filters/elastic-filters.ts
https://meemoo.atlassian.net/browse/ARC-1655
Add a filter option to only receive search result objects that have specific licenses
So we can show only objects with the BEZOEKRERTOOL license on the search page if a user selected a visitor space
```json
{
"size": 39,
"from": 0,
"query": {
"bool": {
"should": [
{
"bool": {
"filter": [],
"must": [
{
"term": {
"schema_maintainer.schema_identifier": "OR-7h1dk9t"
}
},
{
"terms": {
"schema_license": [
"BEZOEKERTOOL-METADATA-ALL",
"BEZOEKERTOOL-CONTENT"
]
}
}
]
}
},
```
before:
after:
> fix(1655): add license filter to filter on objects with bzt license

- src/modules/ie-objects/hooks/get-ie-objects-related.ts
- src/modules/ie-objects/services/ie-objects/ie-objects.service.ts
- src/pages/zoeken/[slug]/[ie]/index.tsx
```
[Nest] 10708  - 09/05/2023, 14:23:48   ERROR [DataService] GraphQl query failed: [{"extensions":{"path":"$.selectionSet.object_ie.args.where.maintainer.schema_identifier._eq","code":"validation-failed"},"message":"unexpected null value for type \"String\""}] +978ms
[Nest] 10708  - 09/05/2023, 14:23:48   ERROR [DataService] Failed to get data from database +0ms
[Nest] 10708  - 09/05/2023, 14:23:48   ERROR [DataService] InternalServerErrorException: Internal Server Error Exception +1ms
[Nest] 10708  - 09/05/2023, 14:23:48   ERROR [ExceptionsHandler] Failed to get data from database, check the logs for more information.
```
> fix(detail): avoid related items call if maintainer id is undefined

- jest.config.js
- src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.helpers.spec.ts
- src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.helpers.ts
- src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
https://meemoo.atlassian.net/browse/ARC-1178
Current implementation:
* select 18:00 as end date if from date is < 17:00
* otherwise take from date + 1 hour
* round to next quarter
* if end date is valid for a newly selected start date, do not modify the end date
main issues were:
* https://stackoverflow.com/questions/13359294/date-getday-javascript-returns-wrong-day
* https://github.com/date-fns/date-fns/issues/3129
> fix(arc-1178): fix date logic for approve visit and add unit tests

- src/styles/abstracts/_variables.scss
- src/styles/pages/admin/_alerts.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1214?focusedCommentId=39290
> fix(arc-1214): align title with table + move notification back

- src/modules/shared/components/MediaCardList/MediaCardList.tsx
- src/pages/zoeken/[slug]/[ie]/index.tsx
https://meemoo.atlassian.net/browse/ARC-1522
http://localhost:3200/zoeken/u-gent/37ed0eaf6e884d6ca4495029e2acdb3afcb13fec72a04eb08904dd275fef86c46e13c0e2bae048eebfbc6477d178ca84
zoeken/:maintainer/:ieObjectId should redirect to zoeken/:maintainer/:ieObjectId/title
but if the title isn't kebabcasable, then the redirect happens to zoeken/:maintainer/:ieObjectId
which causes an infinite loop
So this defaults the title to "titel" if kebabCase(object.name) is falsey
> fix(arc-1522): fix redirect bug if item doesn't have kebabcasable title

- src/modules/shared/types/visit.ts
- src/modules/visitor-space/components/SearchPage/SearchPage.tsx
- src/modules/visitor-space/utils/elastic-filters/elastic-filters.ts
https://meemoo.atlassian.net/browse/ARC-1655
user gets access to folder with 3 objects:
before:
after:
> fix(arc-1655): add filter on objects if the user received folder access

- src/pages/zoeken/[slug]/[ie]/[name]/index.tsx
https://meemoo.atlassian.net/browse/ARC-1685
before:
after:
> fix(arc-1685): make similar objects one column when metadata collapsed

- src/modules/account/components/MaterialRequestDetailBlade/MaterialRequestDetailBlade.module.scss
- src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.module.scss
- src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx
- src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.module.scss
- src/modules/shared/components/VisitDetailBlade/VisitDetailBlade.module.scss
- src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.module.scss
https://meemoo.atlassian.net/browse/ARC-1742
the main issue with the scrolling has already been solved in: https://github.com/viaacode/hetarchief-client/pull/957
before:
after:
> fix(arc-1742): fix title and subtitle styling + add title to scrollable

- src/pages/zoeken/[slug]/[ie]/[name]/index.tsx
- src/pages/zoeken/[slug]/[ie]/index.tsx
https://meemoo.atlassian.net/browse/ARC-1740
When you don't have access we cannot fetch the title of the object to redirect to the /slug/ieObjectId/title url, so the page keeps loading
if you go the the /title url manually, you still get a 404 instead of a no access (403)
before:
after:
> fix(arc-1740): show no access page when no access to object

- src/styles/pages/_object-detail.scss
https://meemoo.atlassian.net/browse/ARC-1743
before:
after:
> fix(arc-1743): add padding to bottom of metadata

- src/modules/visitor-space/const/index.tsx
https://meemoo.atlassian.net/browse/ARC-1777
before:
after:
> fix(arc-1777): hide consultable media filter in visitor space search

- src/modules/account/layouts/AccountLayout/AccountLayout.module.scss
- src/modules/cp/layouts/CPAdminLayout/CPAdminLayout.module.scss
https://meemoo.atlassian.net/browse/ARC-1783
before
after
> fix(arc-1783): reduce titles of account and admin pages on mobile

- src/styles/pages/newsletter/_newsletter.scss
https://meemoo.atlassian.net/browse/ARC-1806
before:
after:
> fix(arc-1806): add a white background + center inputs on mobile

- src/styles/admin-core/_content-pages-preview.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1758
> fix(arc-1758): use same hover color for button in admin core

- src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.module.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1832
> fix(arc-1832): remove top margin from materialrequestblade

- src/modules/shared/components/TagSearchBar/TagSearchBar.types.ts
- src/modules/shared/components/TagSearchBar/TagSearchBarInfo/TagSearchBarInfo.types.ts
- src/modules/visitor-space/components/SearchPage/SearchPage.tsx
Ticket: https://meemoo.atlassian.net/browse/ARC-1852
> fix(arc-1852): show html in tagsearchbarinfo

- src/styles/components/_pagination.scss
Requires react-components PR: https://github.com/viaacode/react-components/pull/96
Ticket: https://meemoo.atlassian.net/browse/ARC-1840
> fix(arc-1840): add padding if many page digits

- src/styles/admin-core/_content-pages.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1749
> fix(arc-1749): add padding to match other admin pages

- src/modules/visitor-space/components/AddToFolderBlade/AddToFolderBlade.module.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1785
> fix(arc-1785): hide outline on focus visible iPad

- src/styles/admin-core/content-blocks/_cards-without-description.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1839
> fix(arc-1839): fix mobile view of cards without description

- src/styles/components/_dropdown.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1851
> fix(arc-1851): fix font family dropdown labels

- src/styles/components/_tags-input.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1827
> fix(arc-1827): long string continues on new line in search

- src/styles/pages/admin/_rewrites.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1122
> fix(arc-1122): hide main image of contentpage

- src/styles/admin-core/_content-pages-preview.scss
Before: 
After:
Ticket: https://meemoo.atlassian.net/browse/ARC-1854
> fix(arc-1854): add margin to show outline button link

- src/modules/shared/services/organisation-service/organisation.service.ts
- src/modules/shared/services/organisation-service/organisation.types.ts
- src/modules/visitor-space/hooks/get-organisation-by-slug.ts
- src/pages/zoeken/[slug]/index.tsx
https://meemoo.atlassian.net/browse/ARC-1878
requires backend PR: https://github.com/viaacode/hetarchief-proxy/pull/451
redirects 
http://localhost:3200/zoeken/rosas
➡️ 
http://localhost:3200/zoeken?aanbieders=OR-cc0ts82---Rosas&format=all&orderDirection=desc&orderProp=relevance&page=1
even if the visitor space does not exist
> feat(arc-1878): use organization instead of visitor space to check slugs

- src/styles/admin-core/_content-pages.scss
https://meemoo.atlassian.net/browse/ARC-1889
so the table fits on a 1440px wide screen
before:
after:
> fix(arc-1889): make content page columns have less padding

- src/styles/pages/_object-detail.scss
https://meemoo.atlassian.net/browse/ARC-1099
example: https://hetarchief.be/zoeken/vrt/44acf5784e854be0bfdc9cd08862065b5af8ab8b4cff444ba9b4d106ab44bb15c86820e53c2b443d8799dbf6f992b8a9/film?tab=metadata
before:
after:
> fix(arc-1099): set scrollable height based on 100vh instead of percent

- src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.module.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1961
> fix(arc-1961): reduce minwidth in sharefolderblade

- src/styles/admin-core/content-blocks/_content-block-image-grid.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1984
> fix(arc-1984): center align imgs in grid

- src/pages/account/mijn-mappen/[folderSlug]/index.tsx
Ticket: https://meemoo.atlassian.net/browse/ARC-1956
> fix(arc-1956): show delete tooltip text to align actions

- src/styles/components/_tooltip.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1941
> fix(arc-1941): fix right arrow of tooltip

- src/modules/shared/components/MetaDataFieldWithHighlightingAndMaxLength/MetaDataFieldWithHighlightingAndMaxLength.tsx
Ticket: https://meemoo.atlassian.net/browse/ARC-1936
> feat(arc-1936): make url clickable metadata identifier

- src/modules/visitor-space/components/GenreFilterForm/GenreFilterForm.tsx
- src/modules/visitor-space/components/GenreSelect/GenreSelect.tsx
- src/modules/visitor-space/components/LanguageFilterForm/LanguageFilterForm.tsx
- src/modules/visitor-space/components/MaintainerFilterForm/MaintainerFilterForm.tsx
- src/modules/visitor-space/components/MediumFilterForm/MediumFilterForm.tsx
- src/modules/visitor-space/components/MediumSelect/MediumSelect.tsx
- src/modules/visitor-space/components/ObjectTypeSelect/ObjectTypeSelect.tsx
- src/modules/visitor-space/utils/sort-filter-options.ts
https://meemoo.atlassian.net/browse/ARC-1943
change default sorting so letters come first, then digits and then special symbols
> feat(arc-1943): sort filter options letters first then digits then rest

- src/styles/admin-core/_content-pages-preview.scss
Before:
After:
Ticket: https://meemoo.atlassian.net/browse/ARC-1942
> fix(arc-1942): fix buttons outline overflowing

- src/pages/bezoek/[slug]/index.tsx
https://meemoo.atlassian.net/browse/ARC-1965
show error when visiting inactive visitor space:
http://localhost:3200/bezoek/industriemuseum
> fix(arc-1965): show visitor space no longer active error

- src/styles/components/_flowplayer.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-1903
> feat(arc-1903): switch overlay logo to right

- src/styles/admin-core/content-blocks/_content-block-two-columns.scss
https://meemoo.atlassian.net/browse/ARC-1960
after desktop:
after mobile:
> fix(ARC-1960): change styling so desktop columns are still 50% of width

- src/styles/components/_content-input.scss
https://meemoo.atlassian.net/browse/ARC-1961
http://localhost:3200/account/mijn-mappen
before:
after:
> fix(ARC-1961): allow long words to be broken in folder name

- src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.module.scss
https://meemoo.atlassian.net/browse/ARC-2008
before:
after:
> fix(ARC-2008): allow word break in obj title in material request blade

- src/pages/bezoek/[slug]/index.tsx
https://meemoo.atlassian.net/browse/ARC-2004
before:
after:
> fix(ARC-2004): show maintainer name instead of slug on no access page

- src/modules/ie-objects/components/ObjectPlaceholder/ObjectPlaceholder.module.scss
https://meemoo.atlassian.net/browse/ARC-2000
before:
after:
> fix(ARC-2000): show no video icon on related objects on mobile

- src/styles/admin-core/_content-pages-preview.scss
https://meemoo.atlassian.net/browse/ARC-1997
before:
after:
> fix(ARC-1997): fix vert alignment in image grid on narrow screens

- src/modules/shared/components/MediaCard/MediaCard.module.scss
- src/modules/shared/components/MediaCard/MediaCard.tsx
Ticket: https://meemoo.atlassian.net/browse/ARC-2001
> fix(arc-2001): whole card disabled view when no link

- src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCard.module.scss
Before:
After:
Ticket: https://meemoo.atlassian.net/browse/ARC-905
> fix(arc-905): use min-width to display icon on iPhone

- src/modules/navigation/components/Navigation/Navigation.module.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-2019
> fix(arc-2019): remove nav items z-index

- src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.helpers.ts
- src/modules/shared/helpers/convert-year-to-date.ts
- src/modules/visitor-space/components/CreatedFilterForm/CreatedFilterForm.tsx
- src/modules/visitor-space/components/DateInput/DateInput.tsx
- src/modules/visitor-space/components/DateRangeInput/DateRangeInput.tsx
- src/modules/visitor-space/components/PublishedFilterForm/PublishedFilterForm.tsx
https://meemoo.atlassian.net/browse/ARC-2023
make default values of date picker filters undefined instead of today
> fix(ARC-2023): make date input component default value empty

- src/modules/navigation/components/Navigation/Navigation.module.scss
Ticket: https://meemoo.atlassian.net/browse/ARC-2033
> fix(arc-2033): navbar highlight fix

- next-i18next.config.js
- src/modules/i18n/helpers/get-translations.ts
- src/pages/admin/vertalingen/TranslationsOverview.module.scss
- src/styles/pages/admin/_translations.scss
https://meemoo.atlassian.net/wiki/spaces/HA2/pages/4212817944/TA+meertaligheid#admin-core-UI-Voorzie-de-admin-core-ui-translations-op-meerdere-talen
translations correctly load on the client side
and the editor looks good:
> feat(translations-sql): use new transl. endp., fix transl.editor styling

- openshift/Jenkinsfile
Every environment should be build using specific parameters. This is to ensure the server-side rendering uses the correct information when pre-rendering components. Change the QAS stage to use the specific client-qas build config.
> ARC-2417 Fix QAS build

- src/modules/shared/components/MediaCard/MediaCard.tsx
on the search page:
http://localhost:3200/zoeken
You would get the console warning:
```
utils.js:90 Image with src "/images/waveform.svg" was detected as the Largest Contentful Paint (LCP). Please add the "priority" property if this image is above the fold.
Read more: https://nextjs.org/docs/api-reference/next/image#priority
```
after this PR the warning is gone:
> fix(performance): add priority to waveform svg image

- src/modules/ie-objects/hooks/get-alto-json-file-content.ts
- src/modules/ie-objects/ie-objects.consts.tsx
- src/modules/ie-objects/services/ie-objects/ie-objects.service.const.ts
- src/modules/ie-objects/services/ie-objects/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-2419
proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/509
also:
* remove 'cm' from dimension units since they already contain 'cm'
* download the alto file through the proxy, since we otherwise have cors issues since the test alto files are on the INT asset service
> feat(ARC-2419): use alto json files instead of larger xml files

- src/modules/search/SearchPage.tsx
https://meemoo.atlassian.net/browse/ARC-2506
https://github.com/user-attachments/assets/2ae1a49a-2ee9-4614-bf07-863583973259
> fix(ARC-2506): scroll to advanced filter when filter menu is collapsed

- openshift/Jenkinsfile
Make sure the Docker image build for INT uses the correct OpenShift build:
- Make separate build for every environment.
- Make build function for reuse.
- After Docker image build, tag image with the short-ref in order to be able to use as rollback if needed.
- Remove some non-used code.
> ARC-2536 Fix INT (Docker image) build

- next.config.js
The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
https://stackoverflow.com/questions/77447587/the-images-domains-configuration-is-deprecated-please-use-images-remotepatte
> fix: fix deprecation warning images config

- src/styles/admin-core/_content-pages.scss
WIth adding the user group selector in the [admin-core](https://github.com/viaacode/react-admin-core-module/pull/306) for AVO, we need to overwrite some of the default styling in Het Archief to avoid a weird layout in the dropdown.
vs
> AVO-37: fix styling for usergroup selector
