viaacode/hetarchief-client

src/modules/shared/components/Button/Button.stories.tsx
src/styles/components/_button.scss

feat(button): add icon button variants

---

src/modules/shared/components/TextInput/TextInput.stories.tsx
src/pages/index.tsx
src/styles/components/_index.scss
src/styles/components/_input.scss

* Added styling and stories for TextInput component

feat(text-input): add styling and stories

---

src/modules/shared/components/Textarea/Textarea.stories.tsx
src/styles/components/_index.scss
src/styles/components/_textarea.scss

* Added Textarea component styling and stories

feat(textarea): add styling and stories

---

openshift/Jenkinsfile
openshift/Makefile

Add the Jenkinsfile and used Makefile.

ARC-339 Create Jenkins pipeline

---

src/modules/reading-room/components/FilterMenu/FilterMenu.module.scss
src/modules/reading-room/components/FilterMenu/FilterMenu.tsx
src/modules/reading-room/components/FilterMenu/FilterMenuMobile/FilterMenuMobile.module.scss
src/modules/reading-room/components/FilterMenu/FilterMenuMobile/FilterMenuMobile.tsx
src/modules/reading-room/components/FilterMenu/FilterMenuMobile/FilterMenuMobile.types.ts
src/modules/reading-room/components/FilterMenu/__mocks__/filter-menu.tsx
src/modules/shared/components/Navigation/Navigation.tsx
src/modules/shared/components/Navigation/Navigation.types.ts
src/modules/shared/components/Navigation/__mocks__/navigation.ts
src/modules/shared/components/Overlay/Overlay.test.tsx
src/pages/leeszaal/[slug].tsx
src/styles/base/_root.scss
src/styles/pages/_reading-room.scss
src/styles/utilities/_text.scss

* Add FilterMenuMobile options
* Update Reading room responsive styling

feat(filter-menu): add filter options on mobile and responsive styling

---

src/modules/shared/const/i18n.tsx
src/modules/shared/const/index.ts
src/modules/shared/wrappers/index.ts
src/modules/shared/wrappers/with-i18n/index.ts
src/modules/shared/wrappers/with-i18n/with-i18n.ts
src/modules/shared/wrappers/with-i18n/with-i18n.types.ts
src/pages/index.tsx
src/pages/leeszaal/[slug].tsx

* Added wrapper for using translations on pages

feat: add i18n wrapper for serverside props

---

package-lock.json
package.json
src/modules/shared/layouts/AppLayout/AppLayout.test.tsx
src/modules/shared/layouts/AppLayout/AppLayout.tsx
src/modules/shared/services/toast-service/index.ts
src/modules/shared/services/toast-service/toast.service.tsx
src/modules/shared/types/index.ts
src/modules/shared/types/utils.ts
src/styles/main.scss
src/styles/vendor/_index.scss
src/styles/vendor/_react-toastify.scss

feat(arc-199): add toast service

---

src/modules/shared/components/ListNavigation/ListNavigation.module.scss
src/modules/shared/components/ListNavigation/ListNavigation.stories.tsx
src/modules/shared/components/ListNavigation/ListNavigation.test.tsx
src/modules/shared/components/ListNavigation/ListNavigation.tsx
src/modules/shared/components/ListNavigation/ListNavigation.types.ts
src/modules/shared/components/ListNavigation/__mocks__/listNavigation.tsx
src/modules/shared/components/Navigation/NavigationDropdown/NavigationDropdown.tsx
src/modules/shared/components/Sidebar/Sidebar.module.scss
src/modules/shared/components/Sidebar/Sidebar.stories.tsx
src/modules/shared/components/Sidebar/Sidebar.test.tsx
src/modules/shared/components/Sidebar/Sidebar.tsx
src/modules/shared/components/Sidebar/Sidebar.types.ts
src/modules/shared/components/Sidebar/index.ts

[ARC-187](https://meemoo.atlassian.net/jira/software/c/projects/ARC/boards/36?modal=detail&selectedIssue=ARC-187)
* prestyled title || ReactNode heading
* children

feat(arc-187): add sidebar component

---

.gitignore
docker-compose.yml

- Ignore intellij files
- add babelrc ignore so i can disable the swc compiler on windows: https://nextjs.org/docs/messages/failed-loading-swc
- fix port in docker to be 3200

fix(gitignore): ignore idea files + babelrc file

---

src/modules/shared/components/ReadingRoomCardControls/ReadingRoomCardControls.module.scss

https://meemoo.atlassian.net/browse/ARC-182?focusedCommentId=28653

Adjust alignment of contact button

---

src/modules/reading-room/components/ReadingRoomNavigation/ReadingRoomNavigation.module.scss
src/modules/shared/components/MediaCard/MediaCard.module.scss
src/modules/shared/components/MediaCardList/MediaCardList.module.scss
src/modules/shared/components/PaginationBar/PaginationBar.module.scss
src/modules/shared/components/PaginationProgress/PaginationProgress.module.scss
src/modules/shared/components/ReadingRoomCard/ReadingRoomCard.module.scss
src/modules/shared/components/ReadingRoomCardControls/ReadingRoomCardControls.module.scss
src/modules/shared/components/ReadingRoomCardList/ReadingRoomCardList.module.scss
src/styles/components/_avatar.scss
src/styles/components/_card.scss
src/styles/components/_datepicker.scss
src/styles/components/_form-control.scss
src/styles/components/_tab.scss
src/styles/components/_table.scss
src/styles/components/_tabs.scss
src/styles/components/_timepicker.scss
src/styles/layouts/_app.scss

Some minor cleanup for consistency

Convert c-selectors to component

---

next-env.d.ts
package-lock.json
src/modules/shared/components/Blade/Blade.module.scss
src/modules/shared/components/Blade/Blade.tsx

Fix issue where blades managed by the blade manager don't fit the overlays

fix(arc-259): add width property for managed blades

---

openshift/Jenkinsfile
openshift/Makefile

Arc 496 tests fail

---

src/modules/media/const/index.tsx
src/pages/leeszaal/[readingRoomSlug]/[objectId]/index.tsx

Media acties gedefinieerd + extra _random_ acties om de `DynamicActionMenu` te testen.

feat(arc-240): define media actions

---

README.md

feat(readme): add docs for storybook deployment

---

src/modules/media/hooks/get-media-objects.ts
src/modules/media/services/media/media.service.ts
src/modules/reading-room/const/index.tsx
src/pages/leeszaal/[readingRoomSlug]/index.tsx

otherwise you would get an error: unexpected param from
while doing the query for media objects.

fix(media): change "from" param to "page" param for the media endpoint

---

.env.template
next.config.js
package-lock.json
src/modules/auth/services/auth-service/auth.service.types.ts
src/modules/auth/store/user/user.slice.ts
src/modules/auth/store/user/user.types.ts
src/modules/auth/types/index.ts
src/modules/shared/services/tos-service/tos.service.ts
src/modules/shared/services/tos-service/tos.service.types.ts
src/modules/shared/types/global.d.ts
src/pages/account/mijn-profiel/index.tsx

https://meemoo.atlassian.net/browse/ARC-184
Note: TST omgeving heeft geen SSUM pagina, dus we gebruiken daar de INT ssum pagina, waardoor je je changes niet zal zien.
The flow is:
`client profile page` => `ssum account edit page` => `proxy logout page` => `client login page` => `client profile page`

feat(arc-184): add SSUM redirect to edit profile info

---

src/pages/_app.tsx

https://meemoo.atlassian.net/browse/ARC-633

fix(arc-633): globally disable react-query's refetch on window refocus

---

src/modules/shared/components/Tabs/ScrollableTabs/ScrollableTabs.module.scss
src/styles/components/_search-bar.scss
src/styles/components/_tab.scss

[ARC-395](https://meemoo.atlassian.net/browse/ARC-395)
- Zachte grijze lijn rond tabs toegevoegd.
- Actief item springt niet meer naar boven.
- Gradients zijn overal zichtbaar en wit.

feat(arc-395): fix gradients, border, active items

---

src/modules/shared/types/media.ts
src/pages/[slug]/[ie]/index.tsx
src/pages/[slug]/index.tsx

- Fix history
- Fix `ook interessant` & `gerelateerde objecten` links

fix(object detail): fix internal links

---

src/pages/[slug]/index.tsx

- Geen thumbnail -> `undefined` ipv `null`

feat(arc-488): add preview fallback

---

src/modules/media/const/index.tsx

- fix client side error on qas

fix(ie): prevent error when abstract is null

---

src/modules/cp/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/cp/components/DeclineRequestBlade/DeclineRequestBlade.tsx

Show summary for each visit request blade:

feat(arc-511): show summary on each visit request blade

---

src/modules/media/hooks/get-media-objects.ts
src/modules/shared/services/events-service/events.service.const.ts
src/modules/shared/services/events-service/events.service.ts
src/modules/shared/services/events-service/events.service.types.ts
src/modules/shared/services/events-service/index.ts
src/pages/[slug]/[ie]/index.tsx

requires backend PR: https://github.com/viaacode/hetarchief-proxy/pull/151
bezoeker voert een zoek opdracht uit
```
{
"id": "474f8d36-864d-4519-b0f3-22b0fd76c55a",
"type": "be.hetarchief.bezoek.search",
"source": "http://localhost:3200/or-rf5kf25",
"subject": "c5a50817-8c56-4a90-8aa0-d77887be5d28",
"time": "2022-04-20T09:33:15.284Z",
"data": {
"slug": "or-rf5kf25",
"filters": [
{
"field": "query",
"operator": "contains"
},
{
"field": "format",
"operator": "is",
"value": "all"
},
{
"field": "creator",
"operator": "is",
"multiValue": []
},
{
"field": "genre",
"operator": "is",
"multiValue": []
},
{
"field": "keyword",
"operator": "is",
"multiValue": []
}
],
"page": 1,
"size": 100,
"sort": {
"orderProp": "relevance"
}
}
}
```
bezoeker bekijkt een object detail pagina
```
{
"id": …
```

feat(arc-769): trigger events for detail page view, video play & search

---

src/modules/auth/components/AuthModal/AuthModal.tsx
src/modules/auth/services/auth-service/auth.service.ts

feat(arc-490): implement redirect for register user button in auth modal

---

src/pages/[slug]/[ie]/index.tsx

fix(date-fns): fix error on object detail page: unexpected export

---

src/modules/navigation/components/Navigation/Navigation.consts.tsx

[ARC-702](https://meemoo.atlassian.net/browse/ARC-702)
- sluit dropdown als je op de current leeszaal klikt

fix(arc-702): close reading room dropdown when clicking current dropdown

---

src/pages/[slug]/[ie]/index.tsx

- Check previous link based on slug

fix(object-detail): fix backlink to search with filters

---

src/modules/navigation/components/Navigation/Navigation.consts.tsx
src/modules/shared/const/routes.ts

- Bezoekersruimtes active state

fix(navigation): bezoekersruimtes active state

---

src/modules/auth/components/AuthModal/AuthModal.tsx

fix(arc-749): icon positioning on safari

---

src/pages/account/mijn-mappen/[collectionSlug]/index.tsx

fix(arc-656): adjust collection metadata properties

---

src/modules/media/components/Metadata/Metadata.module.scss
src/modules/reading-room/components/FilterMenu/FilterMenu.tsx
src/modules/shared/utils/dates.ts
src/pages/[slug]/[ie]/index.tsx
src/pages/[slug]/index.tsx
src/styles/pages/_object-detail.scss

[ARC-253](https://meemoo.atlassian.net/browse/ARC-253)
- Ook interessant in twee kolommen bij expanded metadata
- Fix metadata styling bugs

fix(arc-253): similar layout; layout consistency

---

src/pages/admin/leeszalenbeheer/bezoekers/index.tsx

[ARC-736](https://meemoo.atlassian.net/browse/ARC-736)
- Only query active users

fix(arc-736): only query active users

---

src/modules/navigation/components/Footer/Footer.module.scss
src/modules/navigation/components/Footer/Footer.tsx
src/modules/navigation/components/Footer/__mocks__/footer.tsx

[ARC-160](https://meemoo.atlassian.net/browse/ARC-160)
- tekst boven footer images op één lijn gezet op mobile

fix(arc-160): align footer items

---

src/modules/reading-room/components/CreatedFilterForm/CreatedFilterForm.tsx
src/modules/reading-room/components/DateRangeInput/DateRangeInput.tsx
src/modules/shared/components/MediaCardList/MediaCardList.tsx
src/modules/shared/utils/dates.ts
src/pages/[slug]/index.tsx

- Fix error when only selecting one date in a date range
- Use localised start- & end-OfDay
- Minor cleanup
https://meemoo.atlassian.net/browse/ARC-797
https://meemoo.atlassian.net/browse/ARC-798

Bugfix/arc 798 + 797

---

src/modules/reading-room/const/index.tsx

Beperk aantal items per pagina tot 40

feat(arc-795): limit search results to 40

---

src/modules/media/components/DynamicActionMenu/DynamicActionMenu.test.tsx
src/modules/media/components/DynamicActionMenu/DynamicActionMenu.tsx
src/modules/media/components/DynamicActionMenu/DynamicActionMenu.types.ts
src/modules/media/components/DynamicActionMenu/__mocks__/dynamic-action-menu.tsx
src/modules/media/const/index.tsx
src/modules/media/utils/collections/collections.ts
src/modules/media/utils/collections/index.ts
src/modules/media/utils/index.ts
src/pages/[slug]/[ie]/index.tsx
src/pages/[slug]/index.tsx

- Solid bookmark icon als het object in een folder zit.

feat(arc-265): solid icon when ie is in folder

---

src/styles/pages/admin/_requests.scss

[ARC-805](https://meemoo.atlassian.net/browse/ARC-805)
- admin aanvragen status uitlijning

fix(arc-805): admin aanvragen status uitlijning

---

next.config.js

add image domains to next config

fix(arc-517): next configure image domains

---

src/modules/shared/layouts/AppLayout/AppLayout.tsx
src/setup-tests.ts

That way we can more easily debug deployed versions
```
window.HETARCHIEF_VERSION
```

Feat: Add package.json version to window object

---

src/modules/shared/types/media.ts
src/pages/[slug]/[ie]/index.tsx
src/pages/[slug]/index.tsx

[ARC-253](https://meemoo.atlassian.net/browse/ARC-253)
- Show `maintainer_name` in search and object detail

fix(arc-253): show maintainer name in search and object detail

---

src/pages/[slug]/[ie]/index.tsx

[ARC-801](https://meemoo.atlassian.net/browse/ARC-801)
- Expand metadata button height

fix(arc-801): expand metadata button heigt

---

src/pages/[slug]/[ie]/index.tsx

[ARC-829](https://meemoo.atlassian.net/browse/ARC-829)

fix(arc-829): change description color

---

src/modules/admin/const/Spaces.const.tsx
src/styles/pages/account/_my-profile.scss
src/styles/utilities/_size.scss
src/styles/utilities/_spacers.scss

- Styling fix account > profile
- Fix admin > leeszalenbeheer > leeszalen row height

fix(profile): box bg color

---

src/modules/admin/wrappers/with-admin-core-config.tsx
src/modules/shared/hoc/withAnyRequiredPermissions.tsx
src/pages/admin/content/[id]/bewerk/index.tsx
src/pages/admin/content/index.tsx
src/pages/admin/content/maak/index.tsx

requires PR: https://github.com/viaacode/react-admin-core-module/pull/18
* create content page
* edit content page
* detail of content page
* limit content block options

feat(arc-610): content page edit and create pages

---

src/modules/content-page/hooks/get-content-page.ts
src/modules/content-page/services/content-page.service.const.ts
src/modules/content-page/services/content-page.service.ts
src/modules/content-page/services/content-page.service.types.ts
src/modules/shared/const/query-keys.ts
src/pages/[slug]/index.tsx
src/styles/layouts/_content-block-preview.scss
src/styles/layouts/_index.scss

feat(arc-610): load content page preview when slug is found in url

---

package-lock.json
package.json
src/modules/admin/layouts/AdminLayout/AdminLayout.tsx
src/modules/admin/wrappers/with-admin-core-config.tsx

fix(arc-154): add static links to config, update admin-core, fix navs

---

src/styles/pages/admin/_content-block-form.scss
src/styles/pages/admin/_content-pages.scss
src/styles/pages/admin/_navigation.scss
src/styles/pages/admin/_rewrites.scss

feat(admin): button styling

---

src/modules/admin/const/Spaces.const.tsx
src/modules/cp/components/ReadingRoomSettings/ReadingRoomSettings.tsx
src/modules/cp/components/ReadingRoomSettings/__mocks__/readingRoomSettings.ts
src/modules/home/components/ReadingRoomCardsWithSearch/ReadingRoomCardsWithSearch.tsx
src/modules/navigation/components/Navigation/hooks/get-accessible-reading-rooms.ts
src/modules/reading-room/hooks/get-reading-room.ts
src/modules/reading-room/hooks/get-reading-rooms.ts
src/modules/reading-room/services/visitor-space/index.ts
src/modules/reading-room/services/visitor-space/visitor-space.service.ts
src/modules/reading-room/types/index.ts
src/modules/shared/const/query-keys.ts
src/pages/admin/bezoekersruimtesbeheer/bezoekersruimtes/index.tsx

feat(arc-895): hide non active spaces on homepage, show all for admin

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

waiting page does not flash the search page anymore:
https://user-images.githubusercontent.com/1710840/171194743-ff08d9d6-4c9f-4d6e-b9fe-823ddb83f7fa.mp4
no access page was already fixed:
https://user-images.githubusercontent.com/1710840/171194730-71c345b9-7734-40aa-b17f-045259c7d394.mp4

fix(arc-871): Avoid flash of search page when waiting page should show

---

package-lock.json
package.json
src/styles/pages/admin/_content-pages.scss

fix(arc-891): make content-page preview background white

---

src/modules/home/components/VisitorSpaceCardsWithSearch/VisitorSpaceCardsWithSearch.tsx

mobile button
mobile all shown
desktop button
desktop all shown

fix(arc-856): show the show more button on mobile after 3 spaces

---

src/modules/shared/components/RichTextEditor/RichTextEditor.tsx
src/modules/shared/components/RichTextForm/RichTextForm.tsx
src/styles/components/_rich-text-editor.scss

feat(arc-849): Use correct rich text editor wrapper import

---

src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx

fix(arc-862): do not reset remarks when changing approval dates

---

package-lock.json
src/modules/home/components/LoggedInHome/LoggedInHome.tsx
src/modules/shared/components/DropdownMenu/DropdownMenu.tsx
src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCard.types.ts
src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCardControls/VisitorSpaceCardControls.module.scss
src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCardControls/VisitorSpaceCardControls.tsx
src/modules/shared/components/VisitorSpaceCard/__mocks__/visitor-space-card.ts
src/modules/shared/types/visit.ts
src/modules/visitor-space/types/index.ts

- Show contact info dropdown on homepage 
Needs: https://github.com/viaacode/hetarchief-proxy/pull/205

fix(arc-845): add contact info to planned visits

---

src/modules/admin/const/Spaces.const.tsx
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/MediaCard/MediaCard.test.tsx
src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/visitor-space/components/DateInput/DateInput.tsx
src/pages/account/mijn-mappen/[collectionSlug]/index.tsx

feat(arc-852): change date notation across the app

---

src/maintenance-page/maintanance.html
src/modules/shared/components/CardImage/CardImage.module.scss

fix(arc-844): increase logo size on homepage image cards

---

src/pages/cookiebeleid/index.tsx

https://meemoo.atlassian.net/browse/ARC-161

fix(arc-161): Change timing of loading the cookie bot desclaration

---

src/modules/cp/components/VisitorSpaceSettings/VisitorSpaceSettings.tsx
src/pages/beheer/instellingen/index.tsx

https://meemoo.atlassian.net/browse/ARC-983

fix(arc-983): only redirect to new visitorSpace slug when it changed

---

src/modules/admin/wrappers/with-admin-core-config.tsx

feat(arc-611): add content blocks: intro, imageGrid, uspGrid, quote

---

src/modules/home/components/LoggedOutHome/LoggedOutHome.module.scss
src/modules/home/components/LoggedOutHome/LoggedOutHome.tsx

https://meemoo.atlassian.net/browse/ARC-703
https://user-images.githubusercontent.com/1710840/172619807-9a9e1679-9edf-4e89-88a3-4dc0b7f8079f.mp4

feat(arc-703): Add scroll down indicator

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/pages/[slug]/toegang-aangevraagd/index.tsx

https://meemoo.atlassian.net/browse/ARC-921
kiosk user when trying to visit another space:
kiosk user when trying to visit the access-requested page for another space:

fix(arc-921): Show no access message for kiosk for other spaces/request

---

package.json
src/pages/account/mijn-mappen/[collectionSlug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-933
requires proxy pr: https://github.com/viaacode/hetarchief-proxy/pull/215

feat(arc-933): highlight all fields when searching in folders

---

src/modules/shared/layouts/SidebarLayout/SidebarLayout.module.scss

https://meemoo.atlassian.net/browse/ARC-972

fix(arc-972): Add bottom padding to sidebar layout to avoid overlap

---

src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss

[ARC-839](https://meemoo.atlassian.net/browse/ARC-839)

fix(arc-839): remove grey background sort button

---

src/styles/pages/content-pages/_index.scss

https://meemoo.atlassian.net/browse/ARC-995

fix(arc-995): style rich text editor content just like on avo

---

src/styles/pages/admin/_rewrites.scss

feat(content blocks): add quote styling

---

src/styles/pages/admin/_rewrites.scss

fix(rewrite-css): make u-clickable cursor: pointer

---

src/modules/home/components/LoggedInHome/LoggedInHome.module.scss
src/styles/components/_card.scss

Hover effect op Homepage - Hele card actieve bezoekersruimte, van waar komt dat? >> elk carde card zit dit hover effect

fix(cards): only show hover effect on request cards

---

src/modules/home/components/CancelVisitBlade/CancelVisitBlade.tsx
src/modules/home/components/LoggedInHome/LoggedInHome.tsx
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/DeclineRequestBlade/DeclineRequestBlade.tsx
src/modules/shared/components/ProcessRequestBlade/ProcessRequestBlade.tsx
src/modules/shared/types/blade.ts
src/modules/visitor-space/components/AddToCollectionBlade/AddToCollectionBlade.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/pages/[slug]/[ie]/index.tsx
src/pages/account/mijn-mappen/[collectionSlug]/index.tsx

sluiten van blades heeft 2 clicks nodig waardoor er 2 aanvragen verstuurd worden

fix(forms): disable submit buttons when submitting a form

---

src/modules/home/components/LoggedInHome/LoggedInHome.tsx

https://meemoo.atlassian.net/browse/ARC-1009
before:
after:

fix(arc-1009): Wait for network requests before loading dropdown comps

---

src/modules/shared/hooks/use-scroll-lock/use-scroll-lock.ts

fix(scroll-lock): avoid limiting width to 50% when scroll-lock enabled

---

src/styles/pages/admin/_content-block-form.scss

fix(tags-input): allow tags input to grow with content

---

src/pages/gebruiksvoorwaarden/index.tsx

https://meemoo.atlassian.net/browse/ARC-1022

fix(arc-1022): add 20px margin to the scrollToBottom detection mechanism

---

src/modules/visits/components/VisitRequestsOverview/VisitRequestsOverview.tsx
src/pages/admin/bezoekersruimtesbeheer/actieve-bezoekers/index.tsx
src/pages/admin/bezoekersruimtesbeheer/bezoekersruimtes/index.tsx

https://meemoo.atlassian.net/browse/ARC-1023

fix(arc-1023): reset to first page after search on a paginated table

---

src/pages/admin/gebruikersbeheer/permissies/index.module.scss
src/pages/admin/gebruikersbeheer/permissies/index.tsx

https://meemoo.atlassian.net/browse/ARC-1018
before:
after:

fix(arc-1018): Make columns same width + word break table headers

---

src/styles/pages/admin/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-997
before:
after:

fix(arc-997): Add left and right padding to content pages container

---

src/styles/pages/admin/_rewrites.scss

https://meemoo.atlassian.net/browse/ARC-1019
before:
after:

fix(arc-1019): reduce tag selector height

---

src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx

[ARC-828](https://meemoo.atlassian.net/browse/ARC-828)
remove optional suffix

fix(arc-828): remove optional suffix

---

src/modules/account/types/collections.ts
src/pages/account/mijn-mappen/[collectionSlug]/index.tsx

fix(arc-1064): query meemoo_local_id as identifier bij aanbieder
requires https://github.com/viaacode/hetarchief-proxy/pull/230

arc-1064 identifier bij aanbieder

---

src/pages/[slug]/[ie]/index.tsx

display contact info from visitor space instead of the contact info found on the item

fix(arc-1060): display contact info from visitor space

---

public/locales/nl/common.json
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

add tooltip to bookmark button

feat(arc-938): add tooltip to bookmark button

---

src/pages/[slug]/index.tsx

set content page title as page title

fix(arc-1068): set content page title as page title

---

next.config.js

redirect  /account to /account/mijn-profiel

feat(arc-822): redirect account page

---

src/pages/[slug]/index.tsx
src/pages/cookiebeleid/index.tsx
src/pages/index.tsx

https://meemoo.atlassian.net/browse/ARC-1048

fix(arc-1048): wipe referal state on close

---

src/modules/shared/const/index.ts
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/modules/visitor-space/const/index.tsx

enkel start je zoektocht voor eerste search; daarna alle resultaten

fix(arc-251): update zoekresultaten scherm

---

src/modules/visitor-space/utils/elastic-filters/elastic-filters.ts

enable language filter - not sure why it was commented, maybe there is still a caveat?

fix(arc-1055): enable language filter

---

src/pages/gebruiksvoorwaarden/index.tsx

https://meemoo.atlassian.net/browse/ARC-1022
before:
after

fix(arc-1022): hide zendesk widget on the userconditions page

---

package-lock.json
package.json

by not setting the u-text-left class for left aligned text
since left is the default anyways

fix(arc-1031): allow align on the title in the intro block

---

src/styles/pages/admin/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-1032

fix(arc-1032): set block grid block text color to black

---

src/modules/visitor-space/components/AdvancedFilterFields/AdvancedFilterFields.tsx
src/modules/visitor-space/components/GenreSelect/GenreSelect.tsx
src/modules/visitor-space/components/MediumSelect/MediumSelect.tsx

https://meemoo.atlassian.net/browse/ARC-1081
before:
after:

fix(avo-1081): avoid crash for undef. options, show correct placeholder

---

src/modules/shared/helpers/is-visitor-space-search-page.ts
src/modules/visitor-space/components/VisitorSpaceNavigation/VisitorSpaceNavigation.tsx
src/pages/[slug]/[ie]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1063
before:
after:

fix(arc-1063): show back button on detail page for kiosk users

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

and there are a lot of issues with the current implementation
before:
after:

fix(arc-251): revert changes since the task was out of scope

---

src/modules/auth/services/auth-service/auth.service.ts

https://meemoo.atlassian.net/browse/ARC-1078
redirect after login:

fix(avo-1078): redirect to previous page after login

---

package-lock.json
src/styles/pages/admin/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-1076

fix(avo-1076): reduce heading font sizes on mobile in content pages

---

src/modules/home/components/LoggedInHome/LoggedInHome.tsx
src/modules/shared/const/index.ts
src/modules/shared/hooks/scroll-to-id.ts
src/modules/shared/services/notifications-service/notifications.consts.ts

https://meemoo.atlassian.net/browse/ARC-1067

fix(avo-1067): scroll to planned visits section when clicking view btn

---

src/modules/media/const/index.tsx
src/modules/media/types/index.ts
src/modules/shared/types/media.ts

https://meemoo.atlassian.net/browse/ARC-884
Requires proxy pr: https://github.com/viaacode/hetarchief-proxy/pull/243
before:
after:

fix(avo-884): remove schema_contributor from all media objects

---

package-lock.json
src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCard.module.scss
src/styles/components/_card.scss

https://meemoo.atlassian.net/browse/ARC-1084
before:
after:

fix(avo-1084): remove left and right margin from card title wrapper

---

src/modules/shared/components/MediaCard/MediaCard.tsx

https://meemoo.atlassian.net/browse/ARC-1094

fix(arc-1094): render thumbnail for item type: film

---

src/modules/media/hooks/get-media-objects.ts
src/pages/[slug]/[ie]/index.tsx

https://meemoo.atlassian.net/browse/ARC-774
companion PR in proxy: https://github.com/viaacode/hetarchief-proxy/pull/245

fix(arc-774): improve events according to jira remarks

---

src/styles/pages/admin/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-1034

fix(arc-1034): reduce line-height of the image copyright

---

src/styles/abstracts/_variables.scss
src/styles/components/_button.scss
src/styles/pages/admin/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-1032

fix(arc-1032): remove underline and fix color in grid block

---

src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCardControls/VisitorSpaceCardControls.module.scss

https://meemoo.atlassian.net/browse/ARC-791
before:
after:

fix(arc-791): add margin right to icon in request visit cards

---

package-lock.json
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/visitor-space/components/DateInput/DateInput.tsx
src/modules/visitor-space/components/FilterMenu/FilterButton/FilterButton.tsx
src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss

https://meemoo.atlassian.net/browse/ARC-954

fix(arc-954): a11y

---

src/styles/pages/admin/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-1033

feat(arc-1033): added missing util

---

package-lock.json
package.json

https://meemoo.atlassian.net/browse/AVO-2216

feat(avo-2216): bump dependencies

---

src/modules/home/components/CancelVisitBlade/CancelVisitBlade.tsx
src/modules/home/components/LoggedInHome/LoggedInHome.tsx
src/modules/home/components/ProcessVisitBlade/ProcessVisitBlade.tsx
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/Blade/Blade.stories.tsx
src/modules/shared/components/Blade/Blade.test.tsx
src/modules/shared/components/Blade/Blade.tsx
src/modules/shared/components/Blade/Blade.types.ts
src/modules/shared/components/Blade/__mocks__/blade.tsx
src/modules/shared/components/BladeManager/BladeManager.stories.tsx
src/modules/shared/components/BladeManager/BladeManager.test.tsx
src/modules/shared/components/DeclineRequestBlade/DeclineRequestBlade.tsx
src/modules/shared/components/NotificationCenter/NotificationCenter.tsx
src/modules/shared/components/ProcessRequestBlade/ProcessRequestBlade.tsx
src/modules/shared/helpers/translate.tsx
src/modules/visitor-space/components/AddToFolderBlade/AddToFolderBlade.tsx
src/pages/admin/vertalingen-v2/index.tsx

https://meemoo.atlassian.net/browse/ARC-948

feat(arc-948): make blade headings accessible

---

package-lock.json
src/styles/components/_datepicker.scss

https://meemoo.atlassian.net/browse/ARC-1112

fix(avo-1112): overwrite some rogue styling

---

src/modules/media/components/ObjectPlaceholder/ObjectPlaceholder.types.ts
src/modules/media/const/index.tsx

feat(ARC-964): fix hyperlinks in translations

---

package-lock.json
src/pages/gebruiksvoorwaarden/index.tsx

load http://localhost:3200/gebruiksvoorwaarden directly
before:
after:

fix(arc-1149): fix user conditions page when loading directly

---

src/modules/shared/components/SearchBar/SearchBar.tsx
src/modules/shared/components/SearchBar/SearchBar.types.ts
src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.tsx
src/modules/visitor-space/components/LanguageFilterForm/LanguageFilterForm.tsx
src/modules/visitor-space/components/MediumFilterForm/MediumFilterForm.tsx

feat(ARC-1223): clear searchbar on reset

---

src/modules/account/types/collections.ts
src/modules/shared/components/MediaCard/MediaCard.module.scss
src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/shared/components/MediaCard/MediaCard.types.ts
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

feat(ARC-1267): Add duration to thumbnail in 'mijn mappen'

---

src/modules/admin/wrappers/with-admin-core-config.tsx
src/styles/components/_dropdown.scss

(See admin-core changes: https://github.com/viaacode/react-admin-core-module/pull/106)

feat(ARC-1235): Change styling of UsersOverview

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx

Use the same date format as used in the media cards -> https://meemoo.atlassian.net/browse/ARC-1269?focusedCommentId=37726

feat(mijn-mappen): change date format

---

src/modules/account/layouts/AccountLayout/AccountLayout.tsx
src/modules/admin/layouts/AdminLayout/AdminLayout.tsx
src/modules/cp/const/index.ts
src/modules/cp/layouts/CPAdminLayout/CPAdminLayout.tsx
src/modules/shared/components/ListNavigation/ListNavigation.tsx
src/modules/shared/components/ListNavigation/ListNavigation.types.ts
src/modules/shared/layouts/SidebarLayout/SidebarLayout.module.scss
src/modules/shared/layouts/SidebarLayout/SidebarLayout.test.tsx
src/modules/shared/layouts/SidebarLayout/SidebarLayout.tsx
src/modules/shared/layouts/SidebarLayout/SidebarLayout.types.ts
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1260

feat(cp): add link to sidebar layout

---

scripts/path-aliases.js

fix(path-aliases): add material-requests to jest path config

---

src/modules/navigation/components/Navigation/Navigation.module.scss
src/modules/shared/components/VisitorSpaceDropdown/VisitorSpaceDropdown.module.scss

https://user-images.githubusercontent.com/1710840/221164324-05ce55ce-200f-4d7f-a2d1-71c700339e7a.mp4
https://user-images.githubusercontent.com/1710840/221164347-f53b6133-9b45-4b1a-b77b-439e7fe71fa2.mp4
https://user-images.githubusercontent.com/1710840/221164364-0967d38b-bf6c-4806-9998-e8325b86fb40.mp4
https://user-images.githubusercontent.com/1710840/221164495-be4ccc73-bfe2-4e34-b98f-1b2f95a21c6e.mp4

fix(navigation): make navigation not jump, make dropdown not jump

---

src/modules/shared/components/CheckboxList/CheckboxList.tsx
src/modules/shared/components/CheckboxList/CheckboxList.types.ts
src/modules/shared/components/MultiSelect/MultiSelect.module.scss
src/modules/shared/components/MultiSelect/MultiSelect.stories.tsx
src/modules/shared/components/MultiSelect/MultiSelect.tsx
src/modules/shared/components/MultiSelect/MultiSelect.types.ts
src/modules/shared/components/MultiSelect/index.ts
src/modules/shared/components/index.ts
src/styles/abstracts/_variables.scss
src/styles/components/_dropdown.scss

Create a reusable component so we don't have to style everything multiple times. Will be used on the material request pages and the access page.

feat(MultiSelect): add multi select dropdown component

---

src/modules/account/types/collections.ts
src/modules/shared/components/MediaCard/MediaCard.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1406

bugfix(ARC-1406): Fix thumbnail in 'mijn mappen'

---

next.config.js
src/modules/admin/const/Routing.const.tsx
src/modules/shared/components/ListNavigation/ListNavigation.module.scss
src/modules/shared/components/ListNavigation/ListNavigation.tsx

https://meemoo.atlassian.net/browse/ARC-1421

bugfix(ARC-1421): fix navigation

---

src/modules/cp/layouts/CPAdminLayout/CPAdminLayout.tsx
src/modules/navigation/components/Navigation/Navigation.consts.tsx
src/modules/shared/components/TagSearchBar/TagSearchBar.tsx
src/modules/shared/components/VisitorSpaceDropdown/VisitorSpaceDropdown.tsx
src/modules/shared/components/VisitorSpaceDropdown/VisitorSpaceDropdown.types.ts
src/modules/shared/layouts/AppLayout/AppLayout.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/modules/visitor-space/services/visitor-space/visitor-space.service.ts
src/pages/[slug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1420

feat(arc-1420): fix visitor space dropdown links to point to search page

---

src/modules/ie-objects/utils/extract-snippet-by-search-term.test.ts
src/modules/ie-objects/utils/extract-snippet-by-search-term.ts

https://meemoo.atlassian.net/browse/ARC-1422

feat(arc-1422): add helper to extract part of text by search terms

---

src/modules/shared/components/ListNavigation/ListNavigation.test.tsx

https://meemoo.atlassian.net/browse/ARC-1421

bugfix(ARC-1421): fix test

---

src/styles/components/_pagination.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1160
react-admin-core-module PR: https://github.com/viaacode/react-admin-core-module/pull/128
react-components PR: https://github.com/viaacode/react-components/pull/79

feat(ARC-1160): fix PaginationBar styling

---

src/modules/visitor-space/components/DurationFilterForm/DurationFilterForm.tsx

**TICKET**
https://meemoo.atlassian.net/browse/ARC-1340
**SCREENSHOT**

feat(DurationFilterForm): add background color

---

src/modules/shared/types/index.ts
src/modules/visitor-space/components/DurationFilterForm/DurationFilterForm.tsx
src/modules/visitor-space/components/FilterMenu/FilterForm/FilterForm.module.scss
src/modules/visitor-space/const/metadata.ts
src/modules/visitor-space/utils/map-filters/map-filters.tsx

**TICKET**
https://meemoo.atlassian.net/browse/ARC-1391
**SCREENRECORDING**
https://user-images.githubusercontent.com/77958553/222725474-98033cbe-b63c-4162-b733-0c4dde60ad8f.mov

feat: add exact duration to search filters

---

src/modules/shared/components/ListNavigation/ListNavigation.test.tsx
src/modules/shared/components/ListNavigation/__mocks__/list-navigation.tsx

bugfix(ListNavigationTest): fix test

---

src/modules/navigation/components/Navigation/Navigation.consts.tsx

**TICKET**
https://meemoo.atlassian.net/browse/ARC-1444

feat(Navigation): use unique divider id's

---

src/modules/admin/wrappers/with-admin-core-config.tsx
src/modules/shared/const/routes.ts

https://studiohyperdrive.slack.com/archives/C0279QSL9CZ/p1678222810553139

feat(with-admin-core-config): add missing static route

---

src/modules/shared/components/VisitorSpaceDropdown/VisitorSpaceDropdown.module.scss

Move min-height to the child -> container will automatically grow ;) 
https://meemoo.atlassian.net/browse/ARC-1461
https://user-images.githubusercontent.com/77958553/223735447-a03292e6-c6a9-40a3-964e-3616ef27b70f.mov

fix(VisitorSpaceDropdown): set min-height

---

src/modules/visitor-space/components/SelectDateOrYear/SelectDateOrYear.module.scss

https://meemoo.atlassian.net/browse/ARC-1457

bugfix(ARC-1457): fix z-index radiobuttons

---

src/pages/beheer/materiaalaanvragen/index.tsx

https://meemoo.atlassian.net/browse/ARC-1175
(zie recentste comment)

fix(ARC-1175): Added MaterialRequestDetailBlade to beheer screen

---

src/modules/shared/utils/dates.ts
src/pages/admin/gebruikersbeheer/gebruikers/index.tsx

https://meemoo.atlassian.net/browse/ARC-1160

fix(ARC-1160): remove time from date in UserOverview

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1209
(sorry wrong branchname)

feat(arc-1209): add duration to VisitorSpaceSearchPage

---

src/modules/ie-objects/hooks/get-ie-objects-related.ts
src/modules/ie-objects/services/ie-objects/ie-objects.service.ts

http://localhost:3200/zoeken/vlaams-parlement/d1288c82c96747d7bb6bd6260c4e2db14bcad026f9cf4add9376c22a5c06db421985e236d7fb4b839ffcf2fbe88606cf -> all calls should succeed (no esIndex errors)

feat(ie-objects): replace esIndex with maintainerId

---

package-lock.json
src/modules/shared/components/MediaCard/MediaCard.test.tsx
src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/shared/components/MediaCard/MediaCard.types.ts
src/modules/shared/components/MediaCardList/MediaCardList.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1212
(sorry, used wrong branchname)

feat(arc-1212): add meemooIdentifier to MediaCard

---

src/modules/shared/const/form.ts

https://meemoo.atlassian.net/browse/ARC-1419

fix(form): use updated icons

---

src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/RefinableRadioButton/RefinableRadioButton.tsx
src/modules/shared/components/RefinableRadioButton/RefinableRadioButton.types.ts

https://meemoo.atlassian.net/browse/ARC-1460
http://localhost:3200/admin/bezoekersruimtesbeheer/toegangsaanvragen?aanvraag=491aa706-94c5-47bb-a418-2c93a5dd9507

ARC-1460 Fix initial state for Approve Visit Request Blade

---

src/modules/admin/layouts/AdminLayout/AdminLayout.module.scss

https://meemoo.atlassian.net/browse/ARC-1182

feat(AdminLayout): improve responsive styling

---

package-lock.json
src/modules/admin/wrappers/with-admin-core-config.tsx

customNavigationElements build issue.

fix: add customNavigationElements to admin core config

---

src/modules/shared/components/MediaCardList/MediaCardList.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/styles/pages/_visitor-space.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1506

fix(arc-1506): fix listView

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

https://meemoo.atlassian.net/browse/ARC-1521
https://user-images.githubusercontent.com/77958553/226860760-d75dfc22-dec1-4f20-b61a-c2e7d8bb93f9.mov

feat(VisitorSpaceSearchPage): reset query params when changing vistor spaces

---

package-lock.json
package.json
src/styles/pages/admin/_alerts.scss

Errors moeten visueel bij de correcte input staan.
Admin-core: https://github.com/viaacode/react-admin-core-module/pull/143

fix: mover errors closer to relevant input

---

src/modules/shared/components/MediaCard/MediaCard.tsx

https://user-images.githubusercontent.com/77958553/227022207-f72878e8-c0eb-406e-bb8c-5198153b3ace.mov

feat(MediaCard): remove duration when essence is not available

---

src/modules/ie-objects/types/index.ts
src/pages/zoeken/[slug]/[ie]/index.tsx
src/styles/components/_flowplayer.scss
src/styles/components/_index.scss

https://meemoo.atlassian.net/browse/ARC-1366
requires backend PR: https://github.com/viaacode/hetarchief-proxy/pull/352

feat(arc-1366): add maintainer logo to object detail

---

src/styles/pages/admin/_navigation.scss

fix(back-button): fix admin core back button styling

---

src/modules/shared/const/routes.ts

https://meemoo.atlassian.net/browse/ARC-1568
before:
after:

fix(arc-1568): correctly redirect to waiting page after visit request

---

src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1471

fix(arc-1471): added 'zoeken' to URL

---

public/locales/nl/common.json
src/modules/account/components/MaterialRequestDetailBlade/MaterialRequestDetailBlade.tsx

Ticket (reopened): https://meemoo.atlassian.net/browse/ARC-1165

fix(arc-1165): added organisation defaultvalue to show

---

src/modules/ie-objects/components/DynamicActionMenu/DynamicActionMenu.tsx
src/modules/ie-objects/const/index.tsx
src/pages/zoeken/[slug]/[ie]/index.tsx

**Ticket**
https://meemoo.atlassian.net/browse/ARC-1524
**Screenrecording**
https://user-images.githubusercontent.com/77958553/229071032-f4ff0162-f699-4ef2-9e1f-e95b1e52fbd9.mov

feat(ie): place actions on 1 line

---

package-lock.json
src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx

fix(materialRequest): show organisation if user has organisation

---

src/modules/maintenance-alerts/hooks/get-maintenance-alerts.ts
src/modules/maintenance-alerts/services/maintenance-alerts/maintenance-alerts.service.ts
src/modules/shared/layouts/AppLayout/AppLayout.tsx
tsconfig.json

https://meemoo.atlassian.net/browse/ARC-1542
admin-core PR: https://github.com/viaacode/react-admin-core-module/pull/147
proxy PR: (after admin-core release: update admin-core-api version)
before: no alerts for hetarchief2.0+ateindgebruikerbzt@meemoo.be
after:

fix(arc-1542): fix bugs with user groups for maintenance alerts

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1458

feat(arc-1458): added keyUser styles to mijn mappen

---

src/modules/shared/components/MediaCard/MediaCard.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1232

feat(arc-1232): remove duration when no content

---

src/modules/shared/components/MediaCard/MediaCard.module.scss
src/modules/shared/components/MediaCard/MediaCard.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1233 (zie laatste comment)

feature(ARC-1233): add maintainer logo + fix margin

---

src/pages/zoeken/[slug]/[ie]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1499

fix(arc-1499): fix no essence flash bug

---

src/modules/admin/const/material-requests.const.tsx
src/modules/home/components/VisitorSpaceCardsWithSearch/VisitorSpaceCardsWithSearch.tsx
src/modules/shared/components/SearchBar/SearchBar.tsx
src/modules/shared/components/SearchBar/SearchBar.types.ts
src/modules/shared/const/index.ts
src/modules/shared/utils/create-url.ts
src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.tsx
src/modules/visitor-space/components/GenreFilterForm/GenreFilterForm.tsx
src/modules/visitor-space/components/LanguageFilterForm/LanguageFilterForm.tsx
src/modules/visitor-space/components/MaintainerFilterForm/MaintainerFilterForm.tsx
src/modules/visitor-space/components/MediumFilterForm/MediumFilterForm.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/modules/visitor-space/utils/elastic-filters/elastic-filters.ts
src/modules/visitor-space/utils/map-filters/map-filters.test.tsx
src/modules/visitor-space/utils/map-filters/map-filters.tsx
src/modules/visits/components/VisitRequestsOverview/VisitRequestsOverview.tsx
src/pages/account/mijn-historiek/index.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx
src/pages/admin/bezoekersruimtesbeheer/actieve-bezoekers/index.tsx
src/pages/admin/bezoekersruimtesbeheer/bezoekersruimtes/index.tsx
src/pages/admin/materiaalaanvragen/index.tsx
src/pages/beheer/bezoekers/index.tsx
src/pages/beheer/materiaalaanvragen/index.tsx
src/pages/bezoek/[slug]/toegang-aangevraagd/index.tsx

https://meemoo.atlassian.net/browse/ARC-1592

fix(arc-1592): fix link to visit page, make searchBar a controlled input

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx

**Ticket (reopend)**
https://meemoo.atlassian.net/browse/ARC-1181?focusedCommentId=39968
**Screenshot**

feat(mijn-mappen): add margin

---

src/modules/visitor-space/components/FilterMenu/FilterSort/FilterSort.tsx

**Ticket (reopened)**
https://meemoo.atlassian.net/browse/ARC-1141?focusedCommentId=39969
**Screenrecording**
https://user-images.githubusercontent.com/77958553/231774754-bd84706b-a7d7-4b49-a7d5-f46c1ad1db18.mov

feat(FilterSort): trigger rerender

---

src/modules/shared/components/MediaCardList/MediaCardList.tsx
src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.module.scss
src/modules/shared/services/campaign-monitor-service/campaign-monitor.service.ts
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

bugfix(ARC-1230): fix copy styling + fix sendMail request + fix showLocallyAvailable checks

---

src/styles/admin-core/content-blocks/_three-clickable-tiles.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1168
Admin-core PR: https://github.com/viaacode/react-admin-core-module/pull/162

fix(three-tiles): fix icon + height issue + add outline on hover

---

src/modules/shared/components/MediaCard/MediaCard.test.tsx
src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/shared/components/MediaCard/MediaCard.types.ts
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

Tickets: https://meemoo.atlassian.net/browse/ARC-1458
https://meemoo.atlassian.net/browse/ARC-1628

fix(show-keyuser-label): apply same checks in search/detail/folder pages

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx
src/styles/pages/account/_my-collections.scss
src/styles/utilities/_text.scss

feat(mijn-mappen): fix spacing so it also works on safari

---

package-lock.json
src/styles/admin-core/content-blocks/_cards-without-description.scss

**TICKET**
https://meemoo.atlassian.net/browse/ARC-1621
**INFO**
Needs this admin core PR: https://github.com/viaacode/react-admin-core-module/pull/163
**SCREENSHOT**

feat(cards-without-description): remove fixed background color

---

src/modules/shared/components/TagSearchBar/TagSearchBar.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

https://meemoo.atlassian.net/browse/ARC-1584

fix(arc-1584): remove search field text on empty search results

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/modules/visitor-space/const/index.tsx

fix(filters): hide maintainer filter for kiosk users

---

src/styles/admin-core/content-blocks/_index.scss
src/styles/admin-core/content-blocks/_quote.scss

https://meemoo.atlassian.net/browse/ARC-1215
https://meemoo.atlassian.net/browse/ARC-1337

feat(content-blocks): adjust quote styling

---

src/styles/admin-core/content-blocks/_content-block-two-columns.scss
src/styles/admin-core/content-blocks/_index.scss

https://meemoo.atlassian.net/browse/ARC-1308
https://user-images.githubusercontent.com/77958553/234244375-eac97c67-eb06-46b4-ae0e-56ff3fd29222.mov

feat(content-blocks): overwrite styling

---

public/locales/nl/common.json
src/modules/account/const/my-material-requests.const.tsx
src/modules/admin/const/material-requests.const.tsx
src/modules/cp/const/material-requests.const.tsx
src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx
src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx
src/pages/zoeken/[slug]/[ie]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1165 (see comment with bugtickets)
Backend PR: https://github.com/viaacode/hetarchief-proxy/pull/397

bugfix/ARC-1165: several material request bugfixes

---

src/modules/visits/hooks/get-visits.ts
src/pages/account/mijn-bezoek-historiek/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1618

bugfix/ARC-1618: fix continuous sending of requests in bezoek-historiek

---

src/modules/maintenance-alerts/hooks/get-maintenance-alerts.ts
src/modules/material-requests/hooks/get-material-requests.ts
src/modules/material-requests/hooks/get-pending-material-requests.ts
src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx
src/modules/shared/layouts/AppLayout/AppLayout.tsx
src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx
src/modules/visits/hooks/get-visits.ts

fix(personal): avoid personal api calls for logged out or kiosk users

---

src/pages/zoeken/[slug]/[ie]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1630

fix(arc-1630): fix redirect query params for maintainerMetadataTitle

---

public/locales/nl/common.json
src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.module.scss
src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1230 (last comment)

feature/ARC-1230: Add disclaimer to delen map + fix spacing + reset field on close

---

src/styles/components/_navigation.scss

Tickets: https://meemoo.atlassian.net/browse/ARC-1609
https://meemoo.atlassian.net/browse/ARC-1601

fix(arc-1609-and-1601): fix 2 safari visual issues

---

src/modules/navigation/components/Navigation/Navigation.module.scss
src/modules/shared/components/Overlay/Overlay.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1573

fix(arc-1573): fix background line coming through overlay

---

src/modules/account/components/MaterialRequestDetailBlade/MaterialRequestDetailBlade.tsx
src/modules/material-requests/types/index.ts
src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx
src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx
src/pages/zoeken/[slug]/[ie]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1188 (last comment)

fix(arc-1188): changed propertyname objectDctermsFormat

---

src/modules/home/components/LoggedInHome/LoggedInHome.tsx
src/modules/shared/components/NotificationCenter/NotificationCenter.tsx
src/modules/shared/services/notifications-service/notifications.consts.ts
src/modules/shared/services/notifications-service/notifications.service.ts

https://meemoo.atlassian.net/browse/ARC-1564
https://user-images.githubusercontent.com/1710840/235177445-d4dfb428-7cde-48de-ab8f-40d304f13606.mp4

fix(arc-1564): add correct links to visit notifications

---

package-lock.json
src/modules/ie-objects/const/index.tsx

https://meemoo.atlassian.net/browse/ARC-1343?focusedCommentId=40583
Screenshots (before vs after):

feat(ie-objects): change sort map order for visitors

---

src/modules/navigation/components/Navigation/Navigation.module.scss

fix(profile-dropdown-divider): show divider again

---

src/modules/auth/services/auth-service/auth.service.ts
src/modules/shared/components/ErrorNoAccessToObject/ErrorNoAccessToObject.tsx
src/modules/shared/components/ErrorPage/ErrorPage.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1303

fix(arc-1303): add login modal and fix redirect issue

---

src/modules/visitor-space/components/CreatedFilterForm/CreatedFilterForm.tsx
src/modules/visitor-space/components/DurationFilterForm/DurationFilterForm.tsx
src/modules/visitor-space/components/PublishedFilterForm/PublishedFilterForm.tsx
src/modules/visitor-space/const/metadata.ts
src/modules/visitor-space/utils/metadata/metadata.tsx

fix(empty-filter-dropdowns): add the dropdown options back

---

src/modules/visits/components/VisitRequestsOverview/VisitRequestsOverview.tsx
src/pages/account/mijn-bezoek-historiek/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1638

fix(arc-1638): show same visit results in admin and historiek

---

src/modules/shared/components/MediaCard/MediaCard.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1209

fix(arc-1209): fix duration color

---

src/modules/shared/layouts/AppLayout/AppLayout.tsx

https://meemoo.atlassian.net/browse/ARC-1668
https://user-images.githubusercontent.com/77958553/236194603-68f6235b-79af-43c7-883f-b54538efae41.mov

feat(AppLayout): only only dismiss for logged in users

---

src/modules/visitor-space/components/VisitorSpaceSearchPage/VisitorSpaceSearchPage.tsx

https://meemoo.atlassian.net/browse/ARC-1654

fix(VisitorSpaceSearchPage): check if values intersect

---

src/modules/account/const/index.tsx
src/pages/account/mijn-profiel/index.tsx

https://meemoo.atlassian.net/browse/ARC-1172

feat(mijn-profiel): render key user info for non admin users

---

src/modules/account/const/my-material-requests.const.tsx
src/modules/material-requests/types/index.ts
src/pages/account/mijn-materiaalaanvragen/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1136
Proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/403

fix(arc-1136): fix sorting + show correct date material requests

---

src/pages/zoeken/[slug]/[ie]/index.tsx
src/styles/pages/_object-detail.scss

https://meemoo.atlassian.net/browse/ARC-1661
patch for https://github.com/viaacode/hetarchief-client/pull/858

fix(arc-1662): use the grid to size the image, don't use nextjs img

---

src/modules/admin/wrappers/with-admin-core-config.tsx
src/modules/shared/const/routes.ts
src/styles/admin-core/content-blocks/_hetarchief-header-search-block.scss
src/styles/admin-core/content-blocks/_index.scss

https://meemoo.atlassian.net/browse/ARC-1139
Part of PR group:
* https://github.com/viaacode/hetarchief-client/pull/859
* https://github.com/viaacode/react-admin-core-module/pull/171
desktop:
mobile:

feat(arc-1139): add content block header search

---

public/locales/nl/common.json
src/modules/visitor-space/components/AdvancedFilterForm/AdvancedFilterForm.module.scss
src/modules/visitor-space/components/AdvancedFilterForm/AdvancedFilterForm.tsx
src/modules/visitor-space/utils/select/options.ts

Ticket: https://meemoo.atlassian.net/browse/ARC-1213

fix(arc-1213): fix hidden dropdown + reset dropdown

---

src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss
src/modules/visitor-space/components/FilterMenu/FilterMenu.tsx
src/modules/visitor-space/components/FilterMenu/FilterSort/FilterSort.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1653
Can't seem to find a better solution 👶

fix(arc-1653): fix sorting filter like design

---

src/styles/admin-core/content-blocks/_index.scss
src/styles/admin-core/content-blocks/_rich-text.scss

https://meemoo.atlassian.net/browse/ARC-1679
Part of PR group:
- https://github.com/viaacode/react-admin-core-module/pull/178
- https://github.com/viaacode/hetarchief-client/pull/882

feat(content-blocks): add horizontal line styling

---

src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss

https://meemoo.atlassian.net/browse/ARC-1688
https://user-images.githubusercontent.com/77958553/237059185-85a80de9-e454-43f8-b921-a94e4cc20d56.mov

feat(FilterMenu): set max height

---

src/modules/navigation/components/PersonalInfoBlade/PersonalInfoBlade.tsx

There is a line in https://meemoo.atlassian.net/browse/ARC-1188 that says the blade should close after a succesful send.

fix(blade): close requestblade on send

---

src/pages/zoeken/[slug]/[ie]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1659
Together with proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/406

fix(arc-1659): show correct error on objectDetail page

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1649
before:
after:

fix(arc-1649): remove export metadata button for folders

---

src/modules/visitor-space/components/AddToFolderBlade/AddToFolderBlade.tsx

https://meemoo.atlassian.net/browse/ARC-657
Add / Remove item to/from folder(s):
Add item to multiple folders:
Remove item from multiple folder:
Add item to one folder:
Remove item from one folder:

fix(arc-657): add or remove item from folder(s)

---

src/modules/ie-objects/services/ie-objects/ie-objects.service.ts
src/modules/ie-objects/services/ie-objects/ie-objects.service.types.ts
src/pages/zoeken/[slug]/[ie]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1530

feat(arc-1530): add item description to seo fields on item detail page

---

src/modules/navigation/components/Navigation/NavigationSection/NavigationSection.tsx

https://github.com/viaacode/hetarchief-client/assets/113892598/a517ccc5-d121-4bab-b103-ddfd3e0cee12
Ticket: https://meemoo.atlassian.net/browse/ARC-1642

fix(arc-1642): close materialRequestBlade when clicking in navigationbar

---

src/modules/home/components/LoggedInHome/LoggedInHome.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1650

fix(arc-1650): hide visits with permanent-id on bezoek page

---

public/robots.txt

https://meemoo.atlassian.net/browse/ARC-1529

feat: add robots file

---

src/modules/shared/components/MetaDataDescription/MetaDataDescription.module.scss
src/modules/shared/components/MetaDataDescription/MetaDataDescription.tsx

https://meemoo.atlassian.net/browse/ARC-1699

feat(MetaDataDescription): read more styling

---

src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss
src/modules/visitor-space/components/FilterMenu/FilterSort/FilterSort.tsx
src/styles/utilities/_background.scss

https://meemoo.atlassian.net/browse/ARC-1702

feat(FilterMenu): tweak background and border color

---

src/styles/pages/admin/_rewrites.scss

https://meemoo.atlassian.net/browse/ARC-1701

feat(admin): fix icon size

---

src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.module.scss

https://meemoo.atlassian.net/browse/ARC-1706

feat(MaterialRequestCenterBlade): increase icon font size

---

src/modules/shared/const/routes.ts

https://meemoo.atlassian.net/browse/ARC-1689

feat(routes): remove double closing brackets

---

src/modules/auth/components/AuthModal/AuthModal.tsx

https://meemoo.atlassian.net/browse/ARC-1673?focusedCommentId=40960

feat(AuthModal): tweak background color

---

src/modules/navigation/components/Navigation/Navigation.consts.tsx
src/modules/shared/layouts/AppLayout/AppLayout.tsx

[ARC-1716](https://meemoo.atlassian.net/browse/ARC-1716)
Before: 
After: 
[ARC-1716]: https://meemoo.atlassian.net/browse/ARC-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: don't set an active maintainer for meemoo admins

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1726

feat(folderSlug): hide tooltip text when button is enabled

---

src/modules/visitor-space/components/SearchPage/SearchPage.tsx
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1787
requires proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/426
example page: http://localhost:3200/zoeken/f-abuleus/7aeec9179ecf42158ed85ca9dcd396ed27a927d74b7d4430b7cb2ac72c48a53ac396724137de42acb33c5db96900fa5b/off-the-record
before:
after:

fix(arc-1787): link to correct query param for visitor space

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1710
requires PR: https://github.com/viaacode/hetarchief-client/pull/936
Fix material requests for ugent
test object ugent QAS: http://localhost:3200/zoeken/u-gent/37ed0eaf6e884d6ca4495029e2acdb3afcb13fec72a04eb08904dd275fef86c46e13c0e2bae048eebfbc6477d178ca84/titel

fix(arc-1710): fix ugent material request url params + fix redirect bug

---

src/modules/visitor-space/components/FilterMenu/FilterForm/FilterForm.module.scss
src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss

https://meemoo.atlassian.net/browse/ARC-1735
before:
after:

fix(arc-1735): allow filter menu to be any size, limit options instead

---

public/images/meemoo-logo-background.svg
src/styles/admin-core/_content-pages-preview.scss

https://meemoo.atlassian.net/browse/ARC-1737
requires admin-core pr: https://github.com/viaacode/react-admin-core-module/pull/187
using svg and class instead of crazy selector

fix(arc-1737): fix issues with background logo meemoo

---

src/pages/cookiebeleid/index.tsx

https://meemoo.atlassian.net/browse/ARC-1752
test url: http://localhost:3200/cookiebeleid
before:
after:

fix(arc-1752): fix cookiebot url to include referer

---

src/modules/admin/wrappers/with-admin-core-config.tsx
src/modules/auth/services/auth-service/auth.service.ts
src/modules/content-page/services/content-page-client.service.ts
src/modules/shared/components/ZendeskWrapper/ZendeskWrapper.tsx
src/modules/shared/helpers/get-default-server-side-props.ts
src/modules/shared/helpers/render-og-tags.tsx
src/modules/shared/hooks/use-isomorphic-layout-effect.ts
src/modules/shared/providers/NextQueryParamProvider/NextQueryParamProvider.tsx
src/modules/shared/services/api-service/api.service.ts
src/pages/[slug]/index.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/account/mijn-profiel/index.tsx
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1705
possible fix for:

fix(arc-1705): default to process.env if publicRuntimeConfig is undef

---

src/pages/account/mijn-profiel/index.tsx
src/pages/nieuwsbrief/index.tsx

https://meemoo.atlassian.net/browse/ARC-1285
https://github.com/viaacode/hetarchief-client/assets/1710840/06a1aa56-1f46-49b1-aaac-cbc619346280

feat(arc-1285): newsletter scroll down and back to homepage button

---

src/modules/admin/wrappers/with-admin-core-config.tsx

https://meemoo.atlassian.net/browse/ARC-1757

feat(arc-1757): allow iframe content block to be used

---

src/modules/admin/wrappers/with-admin-core-config.tsx
src/modules/shared/utils/tos.ts
src/pages/gebruiksvoorwaarden/index.module.scss
src/pages/gebruiksvoorwaarden/index.tsx
src/styles/layouts/_app.scss
src/styles/pages/_index.scss

https://meemoo.atlassian.net/browse/ARC-1298
before:
after:

fix(arc-1298): fix scroll issues on the term of service page

---

src/modules/ie-objects/hooks/get-ie-objects.ts

https://meemoo.atlassian.net/browse/ARC-1732
before
after:

fix(arc-1732): reduce filter options for audio/video tab

---

src/styles/admin-core/content-blocks/_image-text-background.scss

https://meemoo.atlassian.net/browse/ARC-1307
requires admin-core-pr: https://github.com/viaacode/react-admin-core-module/pull/189

feat(arc-1307): add styling for 4 image align options in text background

---

src/modules/auth/services/auth-service/auth.service.ts
src/modules/shared/const/query-param-keys.ts
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1713
https://github.com/viaacode/hetarchief-client/assets/1710840/ffc85976-0944-40a4-ac17-b96d4708324b

fix(arc-1713): require login before allowing visitorspace access request

---

src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/shared/components/MediaCardList/MediaCardList.tsx
src/modules/shared/components/MediaCardList/MediaCardList.types.ts
src/modules/visitor-space/components/SearchPage/SearchPage.tsx

https://meemoo.atlassian.net/browse/ARC-1780
before:
after:

fix(arc-1780): wrap whole card in link instead of all text and image

---

src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.module.scss
src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx
src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx

https://meemoo.atlassian.net/browse/ARC-1706
before:
after:

fix(arc-1706): make material request icon larger

---

src/modules/visitor-space/const/index.tsx

https://meemoo.atlassian.net/browse/ARC-1750
before:
after:

fix(arc-1750): hide filter for kiosk user

---

package-lock.json
package.json
src/modules/shared/helpers/translate.tsx
src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx

fix(translations): fix html entities in translations

---

src/modules/visitor-space/const/index.tsx

https://meemoo.atlassian.net/browse/ARC-1630
before:
after:

fix(arc-1630): set default maintainer query param value to undefined

---

src/styles/pages/newsletter/_newsletter.scss

https://meemoo.atlassian.net/browse/ARC-1720
logged out user: http://localhost:3200/nieuwsbrief
before:
after:

fix(arc-1720): add scroll to newsletter page + bottom margin

---

src/modules/navigation/components/Navigation/Navigation.module.scss

fix(mobile-hamburger-menu): make menu scrollable on mobile

---

src/modules/shared/utils/scroll-to-top.ts
src/modules/visitor-space/components/SearchPage/SearchPage.tsx
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1734
scroll to top when using the pagination on the search page

fix(arc-1734): instantly scroll to top for search results pagination

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1800

fix(arc-1800): add required info to view object event

---

src/styles/admin-core/content-blocks/_content-block-two-columns.scss

https://meemoo.atlassian.net/browse/ARC-1763
before:
after:

fix(arc-1763): set width for textbox 2 columns on mobile

---

src/modules/ie-objects/hooks/get-ie-objects.ts
src/modules/shared/services/events-service/events.service.types.ts
src/modules/visitor-space/utils/elastic-filters/elastic-filters.ts

https://meemoo.atlassian.net/browse/ARC-1803

fix(arc-1803): split search into public- and visitor space search events

---

src/modules/shared/components/ZendeskWrapper/ZendeskWrapper.tsx
src/modules/shared/layouts/SidebarLayout/SidebarLayout.module.scss
src/styles/abstracts/_variables.scss
src/styles/pages/_visitor-space.scss

https://meemoo.atlassian.net/browse/ARC-1733
before:
after:

fix(arc-1733): improve positioning feedback button + add padding

---

src/modules/navigation/components/Footer/Footer.module.scss
src/modules/navigation/components/Footer/Footer.tsx

https://meemoo.atlassian.net/browse/ARC-1786
before:
after:

fix(arc-1786): make footer logo display block

---

src/modules/visitor-space/const/metadata.ts

https://meemoo.atlassian.net/browse/ARC-1213

fix(arc-1213): remove genre contains filter options

---

public/locales/nl/common.json
src/modules/ie-objects/hooks/get-ie-objects.ts
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1807

fix(ARC-1807): default user group to anonymous for events

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1811

fix(arc-1811): trigger either visit events or regular events, not both

---

src/pages/bezoek/[slug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1728

fix(arc-1728): show not found error if visitor space is not found

---

src/modules/shared/const/sanitize.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1772

fix(arc-1772): allow <u> and <em> tags

---

src/styles/admin-core/content-blocks/_content-block-image-grid.scss

https://meemoo.atlassian.net/browse/ARC-1240
requires admin-core pr: https://github.com/viaacode/react-admin-core-module/pull/196
https://github.com/viaacode/hetarchief-client/assets/1710840/e1985562-bb94-442f-ba52-5e7b1d262d0d

feat(arc-1240): add image grid option: 30 percent wide

---

src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1744

fix(arc-1744): hide navigation bar when blade is open

---

src/modules/visitor-space/components/FilterMenu/FilterMenu.tsx
src/styles/pages/_object-detail.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1784

fix(arc-1784): fix margin + fix filter + fix safari

---

src/modules/ie-objects/components/DynamicActionMenu/DynamicActionMenu.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1825

fix(arc-1825): hide tooltip if mobile

---

src/pages/account/mijn-bezoek-historiek/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1775

fix(arc-1775): add 'bezoek' to url to fix 404

---

src/styles/admin-core/_content-pages-preview.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1781

fix(arc-1781): fix text color

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1774

fix(arc-1774): add plan een bezoek button to edge case

---

src/styles/components/_pagination.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-928
Screenshot was approved by PM.

fix(arc-928): fix mobile view alignment

---

src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.tsx
src/modules/navigation/components/PersonalInfoBlade/PersonalInfo.types.ts
src/modules/navigation/components/PersonalInfoBlade/PersonalInfoBlade.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1843

fix(arc-1843): add refetch on sendRequests

---

src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.const.ts
src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.tsx
src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.types.ts
src/modules/visitor-space/components/SearchPage/SearchPage.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1835

fix(arc-1835): fix onRemoveTag + creator to type string

---

src/modules/account/utils/index.ts
src/modules/shared/components/MediaCard/MediaCard.module.scss
src/modules/shared/components/MediaCard/MediaCard.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1833

fix(arc-1833): fix placeholder height of mediacard + cleanup

---

src/styles/admin-core/content-blocks/_hetarchief-header-search-block.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1853

fix(arc-1853): edit color of homepage

---

src/styles/admin-core/content-blocks/_rich-text.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1754

fix(arc-1754): remove excess padding

---

src/pages/bezoek/[slug]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1522

fix(arc-1522): fix to show maintainer not active page

---

src/modules/ie-objects/components/Metadata/Metadata.module.scss
src/modules/shared/components/Blade/Blade.module.scss
src/styles/pages/_object-detail.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1870

fix(arc-1870): show new lines in p tags metadata

---

src/modules/navigation/components/Footer/Footer.module.scss
src/modules/navigation/components/Footer/Footer.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1786

fix(arc-1786): dirty fix to show logo on iPhone safari

---

src/modules/visitor-space/utils/elastic-filters/elastic-filters.ts

https://meemoo.atlassian.net/browse/ARC-1848
forgot about this client side code for the already merged proxy changes

fix(arc-1848): pass separate search terms as separate values to proxy

---

package-lock.json
package.json
src/modules/ie-objects/hooks/get-ie-objects-export.ts
src/modules/ie-objects/services/ie-objects/ie-objects.service.ts
src/modules/ie-objects/types/index.ts
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1302
requires backend pr: https://github.com/viaacode/hetarchief-proxy/pull/449
https://github.com/viaacode/hetarchief-client/assets/1710840/928bed92-1932-439d-a487-5f2d374fe319

fix(arc-1302): open backend export metadata route in new tab + force download on mac

---

package-lock.json
src/pages/account/mijn-profiel/index.tsx

https://meemoo.atlassian.net/browse/ARC-1782

fix(arc-1782): show organisation on profile for all users except kiosk

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1883
proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/452

feat(arc-1883): add or_id to events that deal with objects or visits

---

src/modules/visitor-space/components/FilterMenu/FilterMenu.module.scss

https://meemoo.atlassian.net/browse/ARC-1887
before:
after:

fix(arc-1887): reduce z-index of active filter indicator

---

src/styles/pages/admin/_rewrites.scss

https://meemoo.atlassian.net/browse/ARC-1122
before:
after:

fix(arc-1122): hide only content page image and nothing else

---

src/styles/pages/_object-detail.scss

https://meemoo.atlassian.net/browse/ARC-1722
before
after

fix(arc-1722): remove padding of the "also interesting" section

---

src/modules/navigation/components/Footer/Footer.module.scss
src/styles/abstracts/_variables.scss
src/styles/layouts/_container.scss

https://meemoo.atlassian.net/browse/ARC-1837
before:
after:

feat(arc-1837): make all pages and footer 1300px wide max

---

src/styles/admin-core/content-blocks/_content-block-two-columns.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1960

fix(arc-1960): reduce minwidth content-block

---

src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1691

fix(arc-1691): make materialrequestblade primary button

---

src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCard.module.scss
src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCard.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-905

fix(arc-905): expand toggle card description

---

src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/RefinableRadioButton/RefinableRadioButton.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1950

feat(arc-1950): show map labels in requestblade

---

src/modules/account/components/CreateFolderButton/CreateFolderButton.tsx
src/modules/account/components/CreateFolderButton/CreateFolderButton.types.ts
src/modules/visitor-space/components/AddToFolderBlade/AddToFolderBlade.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1946

feat(arc-1946): select new created map

---

src/styles/pages/_object-detail.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1290

fix(arc-1290): videoplayer scales horizontally

---

src/modules/shared/helpers/render-og-tags.tsx
src/pages/[slug]/index.tsx
src/styles/pages/admin/_rewrites.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1122

fix(arc-1122): show main image + meta tag

---

src/pages/cookiebeleid/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1955

fix(arc-1955): fix cookiebeleid url

---

src/modules/shared/components/VisitorSpaceCardList/VisitorSpaceCardList.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-1952

fix(arc-1952): fix alignment spacecard descriptions

---

public/locales/nl/common.json
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.module.scss
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1760

fix(arc-1760): show error in footer accessBlade

---

src/styles/admin-core/_content-pages-edit.scss

https://meemoo.atlassian.net/browse/ARC-1962
before:
after:

fix(arc-1962): reduce file upload spinner height

---

src/modules/account/layouts/AccountLayout/AccountLayout.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1922

fix(arc-1922): hide account history nav link

---

src/modules/account/layouts/AccountLayout/AccountLayout.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1927

fix(arc-1927): hide material request nav item if no permission

---

src/modules/navigation/components/Navigation/Navigation.consts.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1888

feat(arc-1888): hide duplicate nav item on mobile

---

src/pages/account/mijn-mappen/[folderSlug]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1957

fix(arc-1957): folder essence permission fix

---

src/modules/visitor-space/components/FilterMenu/FilterOption/FilterOption.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1939

feat(arc-1939): dynamic filter height

---

src/modules/visitor-space/components/ConsultableOnlyOnLocationFilterForm/ConsultableOnlyOnLocationFilterForm.tsx
src/modules/visitor-space/components/SearchPage/SearchPage.tsx
src/modules/visitor-space/const/index.tsx

https://meemoo.atlassian.net/browse/ARC-1995
after:
https://github.com/viaacode/hetarchief-client/assets/1710840/05a5ea44-95a8-4b3a-88f2-cc2e8f6fe215

fix(ARC-1995): fix pagination on browser back button from detail page

---

src/styles/pages/_object-detail.scss

https://meemoo.atlassian.net/browse/ARC-1290
before:
after:

fix(ARC-1290): fix positioning of the grey bar and the related items

---

src/modules/navigation/components/Navigation/Navigation.module.scss

https://meemoo.atlassian.net/browse/ARC-2010
before:
after:

fix(ARC-2010): remove custom z-index for notifications button

---

src/modules/account/const/index.ts
src/modules/account/layouts/AccountLayout/AccountLayout.tsx
src/modules/navigation/components/Navigation/Navigation.consts.tsx

https://meemoo.atlassian.net/browse/ARC-1927

fix(ARC-1927): minor cleanup to navigation items

---

src/modules/shared/components/MediaCard/MediaCard.module.scss
src/modules/shared/components/MediaCard/MediaCard.tsx

https://meemoo.atlassian.net/browse/ARC-2001
before:
after:

fix(ARC-2001): grey out and show arrow cursor on non clickable obj

---

src/modules/visitor-space/components/LanguageFilterForm/LanguageFilterForm.tsx

https://meemoo.atlassian.net/browse/ARC-1993
before:
after:

fix(ARC-1993): search through language name and language code

---

src/modules/visitor-space/components/AddToFolderBlade/AddToFolderBlade.tsx
src/modules/visitor-space/components/AddToFolderBlade/AddToFolderBlade.types.ts
src/modules/visitor-space/components/SearchPage/SearchPage.tsx
src/pages/account/mijn-mappen/[folderSlug]/index.tsx
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-2016
so it can correctly play the slide in animation and on close disable the focus lock of the blade

fix(ARC-2016): render add to folder blade when page loads

---

src/pages/account/mijn-bezoek-historiek/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1922

fix(arc-1922): show no access page when no permission

---

src/pages/account/mijn-materiaalaanvragen/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1927

fix(arc-1927): show no access if no permission

---

src/modules/navigation/components/MaterialRequestCenterBlade/MaterialRequestCenterBlade.module.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-2008

fix(arc-2008): make long title go on multiple lines

---

src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/shared/components/MediaCard/MediaCard.types.ts
src/modules/shared/components/MediaCardList/MediaCardList.tsx
src/modules/shared/components/MediaCardList/MediaCardList.types.ts
src/pages/account/mijn-mappen/[folderSlug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1957

fix(ARC-1957): split logic for locally available and plan visit buttons

---

public/locales/nl/common.json
src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx
src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-1798

feat(arc-1798): show error on duplicate material request

---

src/modules/shared/layouts/AppLayout/AppLayout.tsx

(can't take screenshot)
Ticket: https://meemoo.atlassian.net/browse/ARC-2011

feat(arc-2011): add timeout to check user on load

---

src/modules/shared/components/VisitorSpaceCard/VisitorSpaceCard.module.scss
src/styles/components/_avatar.scss

Ticket: https://meemoo.atlassian.net/browse/ARC-2009
‼️ React-components branch is needed: https://github.com/viaacode/react-components/pull/98
Or we can close the react-components one and add the aspect ratio here in the client @bertyhell

bugfix: ARC-2009

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

Ticket: https://meemoo.atlassian.net/browse/ARC-2031

fix(arc-2031): check for user first

---

src/modules/shared/const/date.ts
src/modules/shared/helpers/convert-year-to-date.ts
src/modules/visitor-space/components/CreatedFilterForm/CreatedFilterForm.tsx
src/modules/visitor-space/components/PublishedFilterForm/PublishedFilterForm.tsx
src/modules/visitor-space/components/YearRangeInput/YearRangeInput.tsx

https://meemoo.atlassian.net/browse/ARC-2026
year between
https://github.com/viaacode/hetarchief-client/assets/1710840/a5f33670-e739-44ca-8709-7c939e6c3b4c
year until
https://github.com/viaacode/hetarchief-client/assets/1710840/7cebcc3c-b03a-45aa-a919-399911f89ea3
year exact
https://github.com/viaacode/hetarchief-client/assets/1710840/71168bfd-9b95-42fd-bc31-018f5bd97c11

fix(ARC-2026): fix year input filters

---

src/pages/zoeken/[slug]/[ie]/[name]/index.tsx

https://meemoo.atlassian.net/browse/ARC-2039
before: play/pause/play/pause would trigger play events each time
after: only on play event per page load

fix(ARC-2039): trigger play events only once per page

---

next.config.js
src/modules/ie-objects/helpers/isStringOfFormatIeObjectSchemaIdentifier.ts
src/modules/ie-objects/hooks/get-ie-objects-info.ts
src/pages/[slug]/index.tsx

https://meemoo.atlassian.net/browse/ARC-1522
http://localhost:3200/amsab-isg/753bd083cacf4d39af7c0d9924893cc280f929288edc49e3b9702363b22ff19ee61df3f28c344bcd988bd961273470e7
should redirect to:
http://localhost:3200/zoeken/amsab-isg/753bd083cacf4d39af7c0d9924893cc280f929288edc49e3b9702363b22ff19ee61df3f28c344bcd988bd961273470e7/kunstencentrum-vooruit-diamanda-galas-tape-2-september-1999?tab=media
http://localhost:3200/9ac45bfdf2a8410f8b1e320923f622a9493b5f155b254d09a2afed81f42c50bb0b7d9f85ed314331931f230972019c5f
should redirect to:
http://localhost:3200/zoeken/erfgoedcelkerf/9ac45bfdf2a8410f8b1e320923f622a9493b5f155b254d09a2afed81f42c50bb0b7d9f85ed314331931f230972019c5f/eigen-jeugdfilm-rampzalige-bril-gedraaid-in-cinema-alcazar-balen-met-robert-bergmans-richard-vermeulen-en-vele-jongeren? …

fix(ARC-1522): add 2 redirects for amsab-isg and /:id routes

---

src/pages/cookiebeleid/index.tsx

https://meemoo.atlassian.net/browse/ARC-2046
before:
after:

fix(ARC-2046): replace cookiebot crawldate with actual date

---

next.config.js

https://meemoo.atlassian.net/issues/AVO-3238

fix(AVO-3238): add noindex header if environment is localhost or qas

---

.env.template
src/modules/admin/wrappers/with-admin-core-config.tsx
src/modules/content-page/hooks/get-content-page.ts
src/modules/content-page/services/content-page-client.service.ts
src/pages/[slug]/index.tsx
src/pages/api/clear-cache.ts
src/pages/gebruiksvoorwaarden/index.tsx
src/pages/index.tsx
src/styles/admin-core/_content-pages-overview.scss
src/styles/admin-core/_content-pages.scss
src/styles/admin-core/_index.scss

requires admin-core pr: https://github.com/viaacode/react-admin-core-module/pull/240

feat(content-page-multi-language): fix conflicts multi lang admin core

---

src/modules/admin/wrappers/admin-core-config.tsx

This PR has a dependency on the breadcrumb CC in the react-admin-core-module

feat: add breadcrumb component to available components

---

src/modules/auth/services/auth-service/auth.service.ts

https://meemoo.atlassian.net/browse/ARC-2387
requires proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/483

feat(ARC-2387): link to ssum registration page with locale

---

src/modules/navigation/components/Navigation/Navigation.module.scss
src/modules/navigation/components/Navigation/NavigationSection/NavigationSection.tsx
src/modules/navigation/const/index.tsx
src/modules/shared/components/LanguageSwitcher/LanguageSwitcher.module.scss
src/modules/shared/components/LanguageSwitcher/LanguageSwitcher.tsx
src/modules/shared/layouts/AppLayout/AppLayout.module.scss
src/modules/shared/layouts/AppLayout/AppLayout.tsx
src/styles/abstracts/_variables.scss

https://meemoo.atlassian.net/browse/ARC-2084
before:
after:

ARC-2084 language switcher arrow and layout on tablet and mobile

---

src/modules/ie-objects/components/DynamicActionMenu/DynamicActionMenu.tsx

https://meemoo.atlassian.net/browse/ARC-2188

fix(ARC-2188): add overflow ellipsis to meemoo id in search result cards

---

package-lock.json
package.json
src/modules/admin/wrappers/admin-core-config.tsx

https://meemoo.atlassian.net/browse/ARC-2096
requires admin-core pr: https://github.com/viaacode/react-admin-core-module/pull/265

fix(ARC-2096): add enable multilanguage toggle

---

src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/iiif-viewer/IiifViewer.tsx
src/modules/iiif-viewer/IiifViewer.types.ts
src/modules/shared/const/query-param-keys.ts

https://meemoo.atlassian.net/browse/ARC-2240
https://github.com/user-attachments/assets/13159f09-20d9-4400-9d3e-d8641cf8c156

feat(ARC-2240): save zoom and pan position in url

---

package-lock.json
package.json
src/modules/account/const/index.ts
src/modules/account/const/my-folders.const.ts
src/modules/admin/views/MaintenanceAlertsPage.tsx
src/modules/cp/components/VisitorSpaceSettings/VisitorSpaceSettings.const.ts
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.const.ts
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.const.ts
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.types.ts
src/modules/shared/components/DeclineRequestBlade/DeclineRequestBlade.const.ts
src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.consts.ts
src/modules/shared/const/newsletter.ts
src/modules/visitor-space/components/AdvancedFilterForm/AdvancedFilterForm.const.ts
src/modules/visitor-space/components/ConsultableMediaFilterForm/ConsultableMediaFilterForm.const.ts
src/modules/visitor-space/components/ConsultableOnlyOnLocationFilterForm/ConsultableOnlyOnLocationFilterForm.const.ts
src/modules/visitor-space/components/CreatedFilterForm/CreatedFilterForm.const.ts
src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.const.ts
src/modules/visitor-space/components/DurationFilterForm/DurationFilterForm.const.ts
src/modules/visitor-space/components/GenreFilterForm/GenreFilterForm.const.ts
src/modules/visitor-space/components/KeywordsFilterForm/KeywordsFilterForm.const.ts
src/modules/visitor-space/components/LanguageFilterForm/LanguageFilterForm.const.ts
src/modules/visitor-space/components/MaintainerFilterForm/MaintainerFilterForm.const.ts
src/modules/visitor-space/components/MediumFilterForm/MediumFilterForm.const.ts
src/modules/visitor-space/components/PublishedFilterForm/PublishedFilterForm.const.ts
src/modules/visitor-space/components/reportBlade/ReportBlade.const.ts
src/styles/components/_flowplayer.scss

avoid declaring functions inside functions because of unintended closures
also bump yup version to match admin-core yup version
requires admin-core PR: https://github.com/viaacode/react-admin-core-module/pull/267

fix(ARC-2146): fix maintenance alerts description render issues

---

scripts/altos/alto.v3.types.ts
scripts/altos/extract-text-lines-from-alto-internal.ts
src/modules/ie-objects/ObjectDetailPage.module.scss
src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/ie-objects.consts.tsx
src/modules/iiif-viewer/IiifViewer.types.ts

https://meemoo.atlassian.net/browse/ARC-2245

feat(ARC-2245): add ocr metadata to detail page from alto xml

---

src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/components/FragmentSlider/__mocks__/fragmentSlider.tsx
src/modules/ie-objects/components/Metadata/Metadata.types.ts
src/modules/ie-objects/ie-objects.consts.tsx
src/modules/ie-objects/ie-objects.types.ts
src/modules/ie-objects/utils/map-metadata.tsx
src/modules/search/SearchPage.tsx
src/modules/visitor-space/components/LanguageFilterForm/LanguageFilterForm.tsx
src/modules/visitor-space/components/LanguageFilterForm/languages.ts

https://meemoo.atlassian.net/browse/ARC-2163
proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/496

feat(ARC-2163): add newspaper specific metadata + change mapping

---

src/modules/account/services/folders/foldersService.ts

…odal
Feature/arc 2169  add export modal

feat(ARC-2268): update folder share endpoint

---

src/modules/account/views/MyFolders.tsx
src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/utils/get-alto-text-id.ts
src/modules/iiif-viewer/IiifViewer.module.scss
src/modules/iiif-viewer/IiifViewer.tsx
src/modules/iiif-viewer/IiifViewer.types.ts
src/modules/iiif-viewer/components/SearchInputWithResults/SearchInputWithResultsPagination.tsx
src/modules/shared/components/CardImage/CardImage.tsx
src/modules/shared/components/MediaCard/MediaCard.tsx

https://meemoo.atlassian.net/browse/ARC-2235

fix(ARC-2235): Add highlight current search term on newspaper essence

---

src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/components/FragmentSlider/FragmentSlider.stories.tsx
src/modules/ie-objects/components/FragmentSlider/FragmentSlider.tsx
src/modules/ie-objects/components/FragmentSlider/FragmentSlider.types.ts
src/modules/ie-objects/components/FragmentSlider/__mocks__/fragmentSlider.tsx
src/modules/shared/const/query-param-keys.ts
src/pages/pid/[slug]/index.module.scss
src/pages/pid/[slug]/index.tsx
src/styles/abstracts/_variables.scss

https://meemoo.atlassian.net/browse/ARC-2132
example: http://localhost:3200/zoeken/OR-4x54g1p/2v2c846z44/buchenwald-auschwitz
https://github.com/user-attachments/assets/89cd0a93-2804-4019-a98e-bb7daf7b1d99

feat(ARC-2132): show grey bar below video with all representations

---

src/modules/search/SearchPage.tsx
src/modules/visitor-space/const/visitor-space-tabs.const.tsx

https://meemoo.atlassian.net/browse/ARC-2184
before:
after:

feat(ARC-2184): add newspaper tab, show ocr in result card

---

src/modules/navigation/components/Navigation/NavigationDropdown/NavigationDropdown.tsx
src/modules/navigation/components/Navigation/NavigationDropdown/NavigationDropdown.types.ts
src/modules/shared/components/LanguageSwitcher/LanguageSwitcher.module.scss
src/modules/shared/components/LanguageSwitcher/LanguageSwitcher.tsx

https://meemoo.atlassian.net/browse/ARC-2400

fix(ARC-2400): simplify language switcher to correctly react to click

---

src/modules/shared/components/MediaCard/MediaCard.consts.ts
src/modules/shared/components/MediaCard/MediaCard.tsx
src/modules/shared/types/ie-objects.ts

https://meemoo.atlassian.net/browse/ARC-2437
before:
after:

fix(ARC-2437): show "no thumbnail" visualization in folder view

---

src/modules/shared/components/MediaCard/MediaCard.module.scss

https://meemoo.atlassian.net/browse/ARC-2183

feat(ARC-2183): render newspaper on search page in card and list view

---

src/modules/search/SearchPage.tsx
src/modules/shared/components/TagSearchBar/TagSearchBar.tsx
src/modules/shared/components/TagSearchBar/TagSearchBar.types.ts
src/modules/visitor-space/components/FilterMenu/FilterForm/FilterForm.tsx
src/modules/visitor-space/components/FilterMenu/FilterOption/FilterOption.tsx
src/styles/pages/_visitor-space.scss

https://meemoo.atlassian.net/browse/ARC-2218
https://github.com/user-attachments/assets/e1ebb706-efa8-48c0-904d-1d3e98984067

feat(ARC-2218): render advanced filters link + open + scroll down

---

src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/ie-objects.types.ts

https://meemoo.atlassian.net/browse/ARC-2419
requires proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/501

feat(ARC-2419): use alto json if available

---

src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/ie-objects.types.ts
src/modules/shared/helpers/convert-duration-string-to-seconds.ts

https://meemoo.atlassian.net/issues/ARC-2135
This screenshot was made with mock data:

feat(ARC-2135): add cuepoints for start and end of video fragments

---

src/modules/ie-objects/ObjectDetailPage.tsx

https://meemoo.atlassian.net/browse/ARC-2489

fix(ARC-2489): show only metadata warning for non public newspapers

---

package-lock.json
package.json
src/modules/ie-objects/services/ie-objects/ie-objects.service.ts
src/modules/visitor-space/components/AutocompleteFieldInput/AutocompleteFieldInput.module.scss
src/modules/visitor-space/components/AutocompleteFieldInput/AutocompleteFieldInput.tsx
src/modules/visitor-space/components/CreatorFilterForm/CreatorFilterForm.tsx
src/modules/visitor-space/components/FilterMenu/FilterMenu.types.ts

https://meemoo.atlassian.net/browse/ARC-2171

feat(ARC-2171): add autocomplete component for creator filter

---

src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.tsx

fix(ARC-2224): provide errormessages

---

src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/components/ConfidenceIndicator/ConfidenceIndicator.module.scss
src/modules/ie-objects/components/ConfidenceIndicator/ConfidenceIndicator.tsx
src/modules/ie-objects/components/NamesList/NamesList.module.scss
src/modules/ie-objects/components/NamesList/NamesList.tsx
src/modules/ie-objects/components/NamesList/NamesList.types.ts
src/modules/ie-objects/ie-objects.consts.tsx
src/modules/ie-objects/ie-objects.types.ts

https://meemoo.atlassian.net/browse/ARC-2219
proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/519

feat(ARC-2219): get mentions from database

---

src/modules/account/components/CreateFolderButton/CreateFolderButton.tsx
src/modules/account/views/MyProfile.tsx
src/modules/cp/components/VisitorSpaceSettings/VisitorSpaceSettings.tsx
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
src/modules/newsletter/NewsletterPage.tsx
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/DeclineRequestBlade/DeclineRequestBlade.tsx
src/modules/shared/components/RedFormWarning/RedFormWarning.tsx
src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.tsx
src/modules/visitor-space/components/AutocompleteFieldFilterForm/AutocompleteFieldFilterForm.tsx
src/modules/visitor-space/components/DurationFilterForm/DurationFilterForm.tsx
src/modules/visitor-space/components/KeywordsFilterForm/KeywordsFilterForm.tsx
src/modules/visitor-space/components/ReleaseDateFilterForm/ReleaseDateFilterForm.tsx
src/modules/visitor-space/components/reportBlade/ReportBlade.tsx

https://meemoo.atlassian.net/browse/ARC-2149

feat(ARC-2149): add keys to red warning and always return react node

---

.gitignore
package-lock.json
package.json
src/modules/shared/components/MediaCard/MediaCard.module.scss

fix(search): fix regression on search result cards on narrow screens

---

.gitignore
tests/helpers/go-to-page-and-accept-cookies.ts
tests/helpers/is-element-fullscreen.ts
tests/package-lock.json
tests/package.json
tests/tests/t18-test-iiif-viewer-fullscreen.spec.ts

https://meemoo.atlassian.net/browse/ARC-2276
[t18-test-iiif-viewer-fullscreen.webm](https://github.com/user-attachments/assets/50c61315-53ae-4cdb-878f-0cadd1038149)

feat(ARC-2276): add t18 iiif viewer fullscreen

---

tests/helpers/scroll-wheel-over-element.ts
tests/package.json
tests/tests/t18-test-iiif-viewer-fullscreen.spec.ts
tests/tests/t20-test-iiif-viewer-zoomen.spec.ts

https://meemoo.atlassian.net/browse/ARC-2278
[t20-iiif-viewer-zoom-in-out.webm](https://github.com/user-attachments/assets/d97e5448-684a-45f4-9073-6bf3ae2b7fac)

feat(ARC-2278): add end-to-end test to check zoom in and out iiif viewer

---

tests/package.json
tests/tests/t21-test-iiif-viewer-bladeren-paginas.spec.ts

https://meemoo.atlassian.net/issues/ARC-2279
[t21-iiif-viewer-bladeren-paginas.webm](https://github.com/user-attachments/assets/c5313007-50e2-4f02-b666-282244af37ee)

feat(ARC-2279): add end-2-end test to test browsing newspaper pages

---

src/modules/ie-objects/ObjectDetailPage.module.scss
src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/ie-objects/ie-objects.consts.tsx

https://meemoo.atlassian.net/browse/ARC-2513

fix(ARC-2513): hide ocr tab if newspaper doesn't have ocr

---

src/modules/navigation/components/PersonalInfoBlade/PersonalInfoBlade.tsx

https://meemoo.atlassian.net/browse/ARC-2511
proxy PR:https://github.com/viaacode/hetarchief-proxy/pull/523

fix(ARC-2511): do not wait for newsletter when submitting material req

---

src/modules/account/views/MyProfile.tsx

https://meemoo.atlassian.net/browse/ARC-2493

feat(ARC-2493): add locale in change profile info link

---

src/modules/visitor-space/components/AdvancedFilterFields/AdvancedFilterFields.tsx
src/modules/visitor-space/const/advanced-filters.consts.tsx
src/modules/visitor-space/utils/advanced-filters/advanced-filters.utils.tsx

https://meemoo.atlassian.net/browse/ARC-2535

fix(ARC-2535): fix advanced date filter input

---

src/modules/home/components/RequestAccessBlade/RequestAccessBlade.module.scss
src/modules/home/components/RequestAccessBlade/RequestAccessBlade.tsx
src/modules/ie-objects/ObjectDetailPage.module.scss
src/modules/ie-objects/ObjectDetailPage.tsx
src/modules/navigation/components/PersonalInfoBlade/PersonalInfoBlade.tsx
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.module.scss
src/modules/shared/components/ApproveRequestBlade/ApproveRequestBlade.tsx
src/modules/shared/components/RedFormWarning/RedFormWarning.module.scss
src/modules/shared/components/RedFormWarning/RedFormWarning.types.ts
src/modules/visitor-space/components/MaterialRequestBlade/MaterialRequestBlade.module.scss

https://meemoo.atlassian.net/browse/ARC-2224

fix(ARC-2224): show warnings inline in material request form

---

package-lock.json
package.json
tests/helpers/fill-request-visit-blade.ts
tests/helpers/get-site-translations.ts
tests/helpers/login-user-het-archief-idp.ts
tests/helpers/module-class-locator.ts
tests/playwright.config.ts
tests/tests/t01-test-registratie-eerste-keer-inloggen-basisgebruiker.spec.ts
tests/tests/t02-test-inloggen-cp-admin.spec.ts
tests/tests/t03-test-inloggen-meemoo-admin-toegang-aanvragen-tot-bezoekersruimte.spec.ts
tests/tests/t04-test-inloggen-bestaande-basisgebruiker-toegang-aanvragen.spec.ts
tests/tests/t05-test-zoeken-naar-toegang-aanvragen-tot-een-bezoekersruimte.spec.ts
tests/tests/t08-test-faq-raadplegen-niet-ingelogd.spec.ts
tests/tests/t09-test-toegangsaanvraag-accepteren-weigeren-door-cp-admin.spec.ts
tests/tests/t10-test-actieve-toegang-basisgebruiker.spec.ts
tests/tests/t11-test-detailpagina-object.spec.ts
tests/tests/t12-test-einde-sessie-bezoekertool.spec.ts
tests/tests/t13-test-mappen-profielpagina-basisgebruiker.spec.ts
tests/tests/t14-meemoo-beheer-basis-beheersfunctionaliteiten.spec.ts
tests/tests/t15-test-instellingen-cp-beheer.spec.ts
tests/tests/t17-test-gedeeltelijke-toegang-bezoekersruimte.spec.ts
tests/tests/t18-test-iiif-viewer-fullscreen.spec.ts
tests/tests/t19-test-ocr-raadplegen.spec.ts
tests/tests/t21-test-iiif-viewer-bladeren-paginas.spec.ts
tests/tests/t22-test-bronvermelding.spec.ts
tests/tests/t23-test-krant-toevoegen-aan-map.spec.ts

https://meemoo.atlassian.net/browse/ARC-2415
* Add helper to generate selector for modules css classnames [class*="..."__]
* Remove await where not needed
* Fix test 03
* Use db translations in test 03
* Change playwright config to allow js execution in the browser
* Change playwright config to ignore https errors for INT idp
```shell
> cross-env PWDEBUG=console dotenv -e ../.env.local npx playwright test tests/t03-test-inloggen-meemoo-admin-toegang-aanvragen-tot-bezoekersruimte.spec.ts
Running 1 test using 1 worker
t03-test-inloggen-meemoo-admin-toegang-aanvragen-tot-bezoekersruimte.spec.ts:11:5 › T03: Test inloggen meemoo-admin + toegang aanvragen tot bezoekersruimte
1 passed (12.7s)
Process finished with exit code 0
```

fix(ARC-2415): fix test 03, add helper for module classes, use db translations

---

src/modules/navigation/components/PersonalInfoBlade/PersonalInfoBlade.tsx
src/modules/shared/components/ShareFolderBlade/ShareFolderBlade.tsx
src/modules/visitor-space/components/reportBlade/ReportBlade.const.ts
src/modules/visitor-space/components/reportBlade/ReportBlade.tsx
src/modules/visitor-space/components/reportBlade/ReportBlade.types.ts

https://meemoo.atlassian.net/browse/ARC-2148
also removed the usages of the form hooks package, since it adds more code than not using it

feat(ARC-2148): add autocomplete attributes to input fields

---

src/modules/shared/utils/dates.ts

https://meemoo.atlassian.net/browse/ARC-2568

fix(ARC-1920): add check for manage own folder permissions
